//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core/src/main/java/im/actor/model/api/AvatarImage.java
//

#ifndef _APAvatarImage_H_
#define _APAvatarImage_H_

#include "J2ObjC_header.h"
#include "im/actor/model/droidkit/bser/BserObject.h"

@class APFileLocation;
@class BSBserValues;
@class BSBserWriter;

@interface APAvatarImage : BSBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithAPFileLocation:(APFileLocation *)fileLocation
                               withInt:(jint)width
                               withInt:(jint)height
                               withInt:(jint)fileSize;

- (APFileLocation *)getFileLocation;

- (jint)getFileSize;

- (jint)getHeight;

- (jint)getWidth;

- (void)parseWithBSBserValues:(BSBserValues *)values;

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(APAvatarImage)

FOUNDATION_EXPORT void APAvatarImage_initWithAPFileLocation_withInt_withInt_withInt_(APAvatarImage *self, APFileLocation *fileLocation, jint width, jint height, jint fileSize);

FOUNDATION_EXPORT APAvatarImage *new_APAvatarImage_initWithAPFileLocation_withInt_withInt_withInt_(APFileLocation *fileLocation, jint width, jint height, jint fileSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void APAvatarImage_init(APAvatarImage *self);

FOUNDATION_EXPORT APAvatarImage *new_APAvatarImage_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(APAvatarImage)

typedef APAvatarImage ImActorModelApiAvatarImage;

#endif // _APAvatarImage_H_
