//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core/src/main/java/im/actor/model/api/Peer.java
//

#ifndef _APPeer_H_
#define _APPeer_H_

#include "J2ObjC_header.h"
#include "im/actor/model/droidkit/bser/BserObject.h"

@class APPeerTypeEnum;
@class BSBserValues;
@class BSBserWriter;

@interface APPeer : BSBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithAPPeerTypeEnum:(APPeerTypeEnum *)type
                               withInt:(jint)id_;

- (jint)getId;

- (APPeerTypeEnum *)getType;

- (void)parseWithBSBserValues:(BSBserValues *)values;

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(APPeer)

FOUNDATION_EXPORT void APPeer_initWithAPPeerTypeEnum_withInt_(APPeer *self, APPeerTypeEnum *type, jint id_);

FOUNDATION_EXPORT APPeer *new_APPeer_initWithAPPeerTypeEnum_withInt_(APPeerTypeEnum *type, jint id_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void APPeer_init(APPeer *self);

FOUNDATION_EXPORT APPeer *new_APPeer_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(APPeer)

typedef APPeer ImActorModelApiPeer;

#endif // _APPeer_H_
