//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/eac/ECDSAPublicKey.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/math/BigInteger.h"
#include "java/util/Enumeration.h"
#include "org/bouncycastle/asn1/ASN1EncodableVector.h"
#include "org/bouncycastle/asn1/ASN1ObjectIdentifier.h"
#include "org/bouncycastle/asn1/ASN1OctetString.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/DEROctetString.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/DERTaggedObject.h"
#include "org/bouncycastle/asn1/eac/ECDSAPublicKey.h"
#include "org/bouncycastle/asn1/eac/UnsignedInteger.h"

__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setBasePointGWithOrgBouncycastleAsn1ASN1OctetString_(OrgBouncycastleAsn1EacECDSAPublicKey *self, OrgBouncycastleAsn1ASN1OctetString *basePointG);
__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setCofactorFWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *cofactorF);
__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setFirstCoefAWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *firstCoefA);
__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setOrderOfBasePointRWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *orderOfBasePointR);
__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setPrimeModulusPWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *primeModulusP);
__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString_(OrgBouncycastleAsn1EacECDSAPublicKey *self, OrgBouncycastleAsn1ASN1OctetString *publicPointY);
__attribute__((unused)) static void OrgBouncycastleAsn1EacECDSAPublicKey_setSecondCoefBWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *secondCoefB);

@interface OrgBouncycastleAsn1EacECDSAPublicKey () {
 @public
  OrgBouncycastleAsn1ASN1ObjectIdentifier *usage_;
  JavaMathBigInteger *primeModulusP_;
  JavaMathBigInteger *firstCoefA_;
  JavaMathBigInteger *secondCoefB_;
  IOSByteArray *basePointG_;
  JavaMathBigInteger *orderOfBasePointR_;
  IOSByteArray *publicPointY_;
  JavaMathBigInteger *cofactorF_;
  jint options_;
}

- (void)setBasePointGWithOrgBouncycastleAsn1ASN1OctetString:(OrgBouncycastleAsn1ASN1OctetString *)basePointG;

- (void)setCofactorFWithJavaMathBigInteger:(JavaMathBigInteger *)cofactorF;

- (void)setFirstCoefAWithJavaMathBigInteger:(JavaMathBigInteger *)firstCoefA;

- (void)setOrderOfBasePointRWithJavaMathBigInteger:(JavaMathBigInteger *)orderOfBasePointR;

- (void)setPrimeModulusPWithJavaMathBigInteger:(JavaMathBigInteger *)primeModulusP;

- (void)setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString:(OrgBouncycastleAsn1ASN1OctetString *)publicPointY;

- (void)setSecondCoefBWithJavaMathBigInteger:(JavaMathBigInteger *)secondCoefB;
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, usage_, OrgBouncycastleAsn1ASN1ObjectIdentifier *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, primeModulusP_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, firstCoefA_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, secondCoefB_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, basePointG_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, orderOfBasePointR_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, publicPointY_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacECDSAPublicKey, cofactorF_, JavaMathBigInteger *)

@implementation OrgBouncycastleAsn1EacECDSAPublicKey

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq {
  if (self = [super init]) {
    id<JavaUtilEnumeration> en = [((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) getObjects];
    self->usage_ = OrgBouncycastleAsn1ASN1ObjectIdentifier_getInstanceWithId_([((id<JavaUtilEnumeration>) nil_chk(en)) nextElement]);
    options_ = 0;
    while ([en hasMoreElements]) {
      id obj = [en nextElement];
      if ([obj isKindOfClass:[OrgBouncycastleAsn1ASN1TaggedObject class]]) {
        OrgBouncycastleAsn1ASN1TaggedObject *to = (OrgBouncycastleAsn1ASN1TaggedObject *) check_class_cast(obj, [OrgBouncycastleAsn1ASN1TaggedObject class]);
        switch ([((OrgBouncycastleAsn1ASN1TaggedObject *) nil_chk(to)) getTagNo]) {
          case (jint) 0x1:
          OrgBouncycastleAsn1EacECDSAPublicKey_setPrimeModulusPWithJavaMathBigInteger_(self, [((OrgBouncycastleAsn1EacUnsignedInteger *) nil_chk(OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(to))) getValue]);
          break;
          case (jint) 0x2:
          OrgBouncycastleAsn1EacECDSAPublicKey_setFirstCoefAWithJavaMathBigInteger_(self, [((OrgBouncycastleAsn1EacUnsignedInteger *) nil_chk(OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(to))) getValue]);
          break;
          case (jint) 0x3:
          OrgBouncycastleAsn1EacECDSAPublicKey_setSecondCoefBWithJavaMathBigInteger_(self, [((OrgBouncycastleAsn1EacUnsignedInteger *) nil_chk(OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(to))) getValue]);
          break;
          case (jint) 0x4:
          OrgBouncycastleAsn1EacECDSAPublicKey_setBasePointGWithOrgBouncycastleAsn1ASN1OctetString_(self, OrgBouncycastleAsn1ASN1OctetString_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(to, NO));
          break;
          case (jint) 0x5:
          OrgBouncycastleAsn1EacECDSAPublicKey_setOrderOfBasePointRWithJavaMathBigInteger_(self, [((OrgBouncycastleAsn1EacUnsignedInteger *) nil_chk(OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(to))) getValue]);
          break;
          case (jint) 0x6:
          OrgBouncycastleAsn1EacECDSAPublicKey_setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString_(self, OrgBouncycastleAsn1ASN1OctetString_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(to, NO));
          break;
          case (jint) 0x7:
          OrgBouncycastleAsn1EacECDSAPublicKey_setCofactorFWithJavaMathBigInteger_(self, [((OrgBouncycastleAsn1EacUnsignedInteger *) nil_chk(OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(to))) getValue]);
          break;
          default:
          options_ = 0;
          @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Unknown Object Identifier!"];
        }
      }
      else {
        @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Unknown Object Identifier!"];
      }
    }
    if (options_ != (jint) 0x20 && options_ != (jint) 0x7F) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"All options must be either present or absent!"];
    }
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1ObjectIdentifier:(OrgBouncycastleAsn1ASN1ObjectIdentifier *)usage
                                                  withByteArray:(IOSByteArray *)ppY {
  if (self = [super init]) {
    self->usage_ = usage;
    OrgBouncycastleAsn1EacECDSAPublicKey_setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString_(self, [[OrgBouncycastleAsn1DEROctetString alloc] initWithByteArray:ppY]);
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1ObjectIdentifier:(OrgBouncycastleAsn1ASN1ObjectIdentifier *)usage
                                         withJavaMathBigInteger:(JavaMathBigInteger *)p
                                         withJavaMathBigInteger:(JavaMathBigInteger *)a
                                         withJavaMathBigInteger:(JavaMathBigInteger *)b
                                                  withByteArray:(IOSByteArray *)basePoint
                                         withJavaMathBigInteger:(JavaMathBigInteger *)order
                                                  withByteArray:(IOSByteArray *)publicPoint
                                                        withInt:(jint)cofactor {
  if (self = [super init]) {
    self->usage_ = usage;
    OrgBouncycastleAsn1EacECDSAPublicKey_setPrimeModulusPWithJavaMathBigInteger_(self, p);
    OrgBouncycastleAsn1EacECDSAPublicKey_setFirstCoefAWithJavaMathBigInteger_(self, a);
    OrgBouncycastleAsn1EacECDSAPublicKey_setSecondCoefBWithJavaMathBigInteger_(self, b);
    OrgBouncycastleAsn1EacECDSAPublicKey_setBasePointGWithOrgBouncycastleAsn1ASN1OctetString_(self, [[OrgBouncycastleAsn1DEROctetString alloc] initWithByteArray:basePoint]);
    OrgBouncycastleAsn1EacECDSAPublicKey_setOrderOfBasePointRWithJavaMathBigInteger_(self, order);
    OrgBouncycastleAsn1EacECDSAPublicKey_setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString_(self, [[OrgBouncycastleAsn1DEROctetString alloc] initWithByteArray:publicPoint]);
    OrgBouncycastleAsn1EacECDSAPublicKey_setCofactorFWithJavaMathBigInteger_(self, JavaMathBigInteger_valueOfWithLong_(cofactor));
  }
  return self;
}

- (OrgBouncycastleAsn1ASN1ObjectIdentifier *)getUsage {
  return usage_;
}

- (IOSByteArray *)getBasePointG {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_G) != 0) {
    return basePointG_;
  }
  else {
    return nil;
  }
}

- (void)setBasePointGWithOrgBouncycastleAsn1ASN1OctetString:(OrgBouncycastleAsn1ASN1OctetString *)basePointG {
  OrgBouncycastleAsn1EacECDSAPublicKey_setBasePointGWithOrgBouncycastleAsn1ASN1OctetString_(self, basePointG);
}

- (JavaMathBigInteger *)getCofactorF {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_F) != 0) {
    return cofactorF_;
  }
  else {
    return nil;
  }
}

- (void)setCofactorFWithJavaMathBigInteger:(JavaMathBigInteger *)cofactorF {
  OrgBouncycastleAsn1EacECDSAPublicKey_setCofactorFWithJavaMathBigInteger_(self, cofactorF);
}

- (JavaMathBigInteger *)getFirstCoefA {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_A) != 0) {
    return firstCoefA_;
  }
  else {
    return nil;
  }
}

- (void)setFirstCoefAWithJavaMathBigInteger:(JavaMathBigInteger *)firstCoefA {
  OrgBouncycastleAsn1EacECDSAPublicKey_setFirstCoefAWithJavaMathBigInteger_(self, firstCoefA);
}

- (JavaMathBigInteger *)getOrderOfBasePointR {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_R) != 0) {
    return orderOfBasePointR_;
  }
  else {
    return nil;
  }
}

- (void)setOrderOfBasePointRWithJavaMathBigInteger:(JavaMathBigInteger *)orderOfBasePointR {
  OrgBouncycastleAsn1EacECDSAPublicKey_setOrderOfBasePointRWithJavaMathBigInteger_(self, orderOfBasePointR);
}

- (JavaMathBigInteger *)getPrimeModulusP {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_P) != 0) {
    return primeModulusP_;
  }
  else {
    return nil;
  }
}

- (void)setPrimeModulusPWithJavaMathBigInteger:(JavaMathBigInteger *)primeModulusP {
  OrgBouncycastleAsn1EacECDSAPublicKey_setPrimeModulusPWithJavaMathBigInteger_(self, primeModulusP);
}

- (IOSByteArray *)getPublicPointY {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_Y) != 0) {
    return publicPointY_;
  }
  else {
    return nil;
  }
}

- (void)setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString:(OrgBouncycastleAsn1ASN1OctetString *)publicPointY {
  OrgBouncycastleAsn1EacECDSAPublicKey_setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString_(self, publicPointY);
}

- (JavaMathBigInteger *)getSecondCoefB {
  if ((options_ & OrgBouncycastleAsn1EacECDSAPublicKey_B) != 0) {
    return secondCoefB_;
  }
  else {
    return nil;
  }
}

- (void)setSecondCoefBWithJavaMathBigInteger:(JavaMathBigInteger *)secondCoefB {
  OrgBouncycastleAsn1EacECDSAPublicKey_setSecondCoefBWithJavaMathBigInteger_(self, secondCoefB);
}

- (jboolean)hasParameters {
  return primeModulusP_ != nil;
}

- (OrgBouncycastleAsn1ASN1EncodableVector *)getASN1EncodableVectorWithOrgBouncycastleAsn1ASN1ObjectIdentifier:(OrgBouncycastleAsn1ASN1ObjectIdentifier *)oid
                                                                                                  withBoolean:(jboolean)publicPointOnly {
  OrgBouncycastleAsn1ASN1EncodableVector *v = [[OrgBouncycastleAsn1ASN1EncodableVector alloc] init];
  [v addWithOrgBouncycastleAsn1ASN1Encodable:oid];
  if (!publicPointOnly) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1EacUnsignedInteger alloc] initWithInt:(jint) 0x01 withJavaMathBigInteger:[self getPrimeModulusP]]];
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1EacUnsignedInteger alloc] initWithInt:(jint) 0x02 withJavaMathBigInteger:[self getFirstCoefA]]];
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1EacUnsignedInteger alloc] initWithInt:(jint) 0x03 withJavaMathBigInteger:[self getSecondCoefB]]];
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DERTaggedObject alloc] initWithBoolean:NO withInt:(jint) 0x04 withOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DEROctetString alloc] initWithByteArray:[self getBasePointG]]]];
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1EacUnsignedInteger alloc] initWithInt:(jint) 0x05 withJavaMathBigInteger:[self getOrderOfBasePointR]]];
  }
  [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DERTaggedObject alloc] initWithBoolean:NO withInt:(jint) 0x06 withOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DEROctetString alloc] initWithByteArray:[self getPublicPointY]]]];
  if (!publicPointOnly) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1EacUnsignedInteger alloc] initWithInt:(jint) 0x07 withJavaMathBigInteger:[self getCofactorF]]];
  }
  return v;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return [[OrgBouncycastleAsn1DERSequence alloc] initWithOrgBouncycastleAsn1ASN1EncodableVector:[self getASN1EncodableVectorWithOrgBouncycastleAsn1ASN1ObjectIdentifier:usage_ withBoolean:NO]];
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1EacECDSAPublicKey *)other {
  [super copyAllFieldsTo:other];
  other->usage_ = usage_;
  other->primeModulusP_ = primeModulusP_;
  other->firstCoefA_ = firstCoefA_;
  other->secondCoefB_ = secondCoefB_;
  other->basePointG_ = basePointG_;
  other->orderOfBasePointR_ = orderOfBasePointR_;
  other->publicPointY_ = publicPointY_;
  other->cofactorF_ = cofactorF_;
  other->options_ = options_;
}

@end

void OrgBouncycastleAsn1EacECDSAPublicKey_setBasePointGWithOrgBouncycastleAsn1ASN1OctetString_(OrgBouncycastleAsn1EacECDSAPublicKey *self, OrgBouncycastleAsn1ASN1OctetString *basePointG) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_G) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_G;
    self->basePointG_ = [((OrgBouncycastleAsn1ASN1OctetString *) nil_chk(basePointG)) getOctets];
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Base Point G already set"];
  }
}

void OrgBouncycastleAsn1EacECDSAPublicKey_setCofactorFWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *cofactorF) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_F) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_F;
    self->cofactorF_ = cofactorF;
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Cofactor F already set"];
  }
}

void OrgBouncycastleAsn1EacECDSAPublicKey_setFirstCoefAWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *firstCoefA) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_A) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_A;
    self->firstCoefA_ = firstCoefA;
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"First Coef A already set"];
  }
}

void OrgBouncycastleAsn1EacECDSAPublicKey_setOrderOfBasePointRWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *orderOfBasePointR) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_R) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_R;
    self->orderOfBasePointR_ = orderOfBasePointR;
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Order of base point R already set"];
  }
}

void OrgBouncycastleAsn1EacECDSAPublicKey_setPrimeModulusPWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *primeModulusP) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_P) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_P;
    self->primeModulusP_ = primeModulusP;
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Prime Modulus P already set"];
  }
}

void OrgBouncycastleAsn1EacECDSAPublicKey_setPublicPointYWithOrgBouncycastleAsn1ASN1OctetString_(OrgBouncycastleAsn1EacECDSAPublicKey *self, OrgBouncycastleAsn1ASN1OctetString *publicPointY) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_Y) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_Y;
    self->publicPointY_ = [((OrgBouncycastleAsn1ASN1OctetString *) nil_chk(publicPointY)) getOctets];
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Public Point Y already set"];
  }
}

void OrgBouncycastleAsn1EacECDSAPublicKey_setSecondCoefBWithJavaMathBigInteger_(OrgBouncycastleAsn1EacECDSAPublicKey *self, JavaMathBigInteger *secondCoefB) {
  if ((self->options_ & OrgBouncycastleAsn1EacECDSAPublicKey_B) == 0) {
    self->options_ |= OrgBouncycastleAsn1EacECDSAPublicKey_B;
    self->secondCoefB_ = secondCoefB;
  }
  else {
    @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Second Coef B already set"];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1EacECDSAPublicKey)
