//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/eac/UnsignedInteger.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/System.h"
#include "java/math/BigInteger.h"
#include "org/bouncycastle/asn1/ASN1OctetString.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/DEROctetString.h"
#include "org/bouncycastle/asn1/DERTaggedObject.h"
#include "org/bouncycastle/asn1/eac/UnsignedInteger.h"

__attribute__((unused)) static IOSByteArray *OrgBouncycastleAsn1EacUnsignedInteger_convertValue(OrgBouncycastleAsn1EacUnsignedInteger *self);

@interface OrgBouncycastleAsn1EacUnsignedInteger () {
 @public
  jint tagNo_;
  JavaMathBigInteger *value_;
}
- (instancetype)initWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj;

- (IOSByteArray *)convertValue;
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EacUnsignedInteger, value_, JavaMathBigInteger *)

@implementation OrgBouncycastleAsn1EacUnsignedInteger

- (instancetype)initWithInt:(jint)tagNo
     withJavaMathBigInteger:(JavaMathBigInteger *)value {
  if (self = [super init]) {
    self->tagNo_ = tagNo;
    self->value_ = value;
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj {
  if (self = [super init]) {
    self->tagNo_ = [((OrgBouncycastleAsn1ASN1TaggedObject *) nil_chk(obj)) getTagNo];
    self->value_ = [[JavaMathBigInteger alloc] initWithInt:1 withByteArray:[((OrgBouncycastleAsn1ASN1OctetString *) nil_chk(OrgBouncycastleAsn1ASN1OctetString_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, NO))) getOctets]];
  }
  return self;
}

+ (OrgBouncycastleAsn1EacUnsignedInteger *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(obj);
}

- (IOSByteArray *)convertValue {
  return OrgBouncycastleAsn1EacUnsignedInteger_convertValue(self);
}

- (jint)getTagNo {
  return tagNo_;
}

- (JavaMathBigInteger *)getValue {
  return value_;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return [[OrgBouncycastleAsn1DERTaggedObject alloc] initWithBoolean:NO withInt:tagNo_ withOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DEROctetString alloc] initWithByteArray:OrgBouncycastleAsn1EacUnsignedInteger_convertValue(self)]];
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1EacUnsignedInteger *)other {
  [super copyAllFieldsTo:other];
  other->tagNo_ = tagNo_;
  other->value_ = value_;
}

@end

OrgBouncycastleAsn1EacUnsignedInteger *OrgBouncycastleAsn1EacUnsignedInteger_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1EacUnsignedInteger_init();
  if ([obj isKindOfClass:[OrgBouncycastleAsn1EacUnsignedInteger class]]) {
    return (OrgBouncycastleAsn1EacUnsignedInteger *) check_class_cast(obj, [OrgBouncycastleAsn1EacUnsignedInteger class]);
  }
  if (obj != nil) {
    return [[OrgBouncycastleAsn1EacUnsignedInteger alloc] initWithOrgBouncycastleAsn1ASN1TaggedObject:OrgBouncycastleAsn1ASN1TaggedObject_getInstanceWithId_(obj)];
  }
  return nil;
}

IOSByteArray *OrgBouncycastleAsn1EacUnsignedInteger_convertValue(OrgBouncycastleAsn1EacUnsignedInteger *self) {
  IOSByteArray *v = [((JavaMathBigInteger *) nil_chk(self->value_)) toByteArray];
  if (IOSByteArray_Get(nil_chk(v), 0) == 0) {
    IOSByteArray *tmp = [IOSByteArray newArrayWithLength:v->size_ - 1];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(v, 1, tmp, 0, tmp->size_);
    return tmp;
  }
  return v;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1EacUnsignedInteger)
