//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/x509/RoleSyntax.java
//

#ifndef _OrgBouncycastleAsn1X509RoleSyntax_H_
#define _OrgBouncycastleAsn1X509RoleSyntax_H_

@class IOSObjectArray;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Sequence;
@class OrgBouncycastleAsn1X509GeneralName;
@class OrgBouncycastleAsn1X509GeneralNames;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

@interface OrgBouncycastleAsn1X509RoleSyntax : OrgBouncycastleAsn1ASN1Object {
}

+ (OrgBouncycastleAsn1X509RoleSyntax *)getInstanceWithId:(id)obj;

- (instancetype)initWithOrgBouncycastleAsn1X509GeneralNames:(OrgBouncycastleAsn1X509GeneralNames *)roleAuthority
                     withOrgBouncycastleAsn1X509GeneralName:(OrgBouncycastleAsn1X509GeneralName *)roleName;

- (instancetype)initWithOrgBouncycastleAsn1X509GeneralName:(OrgBouncycastleAsn1X509GeneralName *)roleName;

- (instancetype)initWithNSString:(NSString *)roleName;

- (OrgBouncycastleAsn1X509GeneralNames *)getRoleAuthority;

- (OrgBouncycastleAsn1X509GeneralName *)getRoleName;

- (NSString *)getRoleNameAsString;

- (IOSObjectArray *)getRoleAuthorityAsString;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1X509RoleSyntax)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1X509RoleSyntax *OrgBouncycastleAsn1X509RoleSyntax_getInstanceWithId_(id obj);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1X509RoleSyntax)

#endif // _OrgBouncycastleAsn1X509RoleSyntax_H_
