//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/x509/TargetInformation.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/util/Enumeration.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/x509/TargetInformation.h"
#include "org/bouncycastle/asn1/x509/Targets.h"

@interface OrgBouncycastleAsn1X509TargetInformation () {
 @public
  OrgBouncycastleAsn1ASN1Sequence *targets_;
}
- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq;
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1X509TargetInformation, targets_, OrgBouncycastleAsn1ASN1Sequence *)

@implementation OrgBouncycastleAsn1X509TargetInformation

+ (OrgBouncycastleAsn1X509TargetInformation *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1X509TargetInformation_getInstanceWithId_(obj);
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq {
  if (self = [super init]) {
    targets_ = seq;
  }
  return self;
}

- (IOSObjectArray *)getTargetsObjects {
  IOSObjectArray *copy_ = [IOSObjectArray newArrayWithLength:[((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(targets_)) size] type:OrgBouncycastleAsn1X509Targets_class_()];
  jint count = 0;
  for (id<JavaUtilEnumeration> e = [targets_ getObjects]; [((id<JavaUtilEnumeration>) nil_chk(e)) hasMoreElements]; ) {
    IOSObjectArray_Set(copy_, count++, OrgBouncycastleAsn1X509Targets_getInstanceWithId_([e nextElement]));
  }
  return copy_;
}

- (instancetype)initOrgBouncycastleAsn1X509TargetInformationWithOrgBouncycastleAsn1X509Targets:(OrgBouncycastleAsn1X509Targets *)targets {
  if (self = [super init]) {
    self->targets_ = [[OrgBouncycastleAsn1DERSequence alloc] initWithOrgBouncycastleAsn1ASN1Encodable:targets];
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1X509Targets:(OrgBouncycastleAsn1X509Targets *)targets {
  return [self initOrgBouncycastleAsn1X509TargetInformationWithOrgBouncycastleAsn1X509Targets:targets];
}

- (instancetype)initWithOrgBouncycastleAsn1X509TargetArray:(IOSObjectArray *)targets {
  return [self initOrgBouncycastleAsn1X509TargetInformationWithOrgBouncycastleAsn1X509Targets:[[OrgBouncycastleAsn1X509Targets alloc] initWithOrgBouncycastleAsn1X509TargetArray:targets]];
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return targets_;
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1X509TargetInformation *)other {
  [super copyAllFieldsTo:other];
  other->targets_ = targets_;
}

@end

OrgBouncycastleAsn1X509TargetInformation *OrgBouncycastleAsn1X509TargetInformation_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1X509TargetInformation_init();
  if ([obj isKindOfClass:[OrgBouncycastleAsn1X509TargetInformation class]]) {
    return (OrgBouncycastleAsn1X509TargetInformation *) check_class_cast(obj, [OrgBouncycastleAsn1X509TargetInformation class]);
  }
  else if (obj != nil) {
    return [[OrgBouncycastleAsn1X509TargetInformation alloc] initWithOrgBouncycastleAsn1ASN1Sequence:OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(obj)];
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509TargetInformation)
