//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/x509/TBSCertList.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/math/BigInteger.h"
#include "java/util/Enumeration.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1EncodableVector.h"
#include "org/bouncycastle/asn1/ASN1GeneralizedTime.h"
#include "org/bouncycastle/asn1/ASN1Integer.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/ASN1UTCTime.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/DERTaggedObject.h"
#include "org/bouncycastle/asn1/x500/X500Name.h"
#include "org/bouncycastle/asn1/x509/AlgorithmIdentifier.h"
#include "org/bouncycastle/asn1/x509/Extensions.h"
#include "org/bouncycastle/asn1/x509/TBSCertList.h"
#include "org/bouncycastle/asn1/x509/Time.h"

@interface OrgBouncycastleAsn1X509TBSCertList_CRLEntry ()
- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq;
@end

@interface OrgBouncycastleAsn1X509TBSCertList_RevokedCertificatesEnumeration () {
 @public
  id<JavaUtilEnumeration> en_;
}
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1X509TBSCertList_RevokedCertificatesEnumeration, en_, id<JavaUtilEnumeration>)

@implementation OrgBouncycastleAsn1X509TBSCertList

+ (OrgBouncycastleAsn1X509TBSCertList *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                               withBoolean:(jboolean)explicit_ {
  return OrgBouncycastleAsn1X509TBSCertList_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, explicit_);
}

+ (OrgBouncycastleAsn1X509TBSCertList *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1X509TBSCertList_getInstanceWithId_(obj);
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq {
  if (self = [super init]) {
    if ([((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) size] < 3 || [seq size] > 7) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:JreStrcat("$I", @"Bad sequence size: ", [seq size])];
    }
    jint seqPos = 0;
    if ([[seq getObjectAtWithInt:seqPos] isKindOfClass:[OrgBouncycastleAsn1ASN1Integer class]]) {
      version__ = OrgBouncycastleAsn1ASN1Integer_getInstanceWithId_([seq getObjectAtWithInt:seqPos++]);
    }
    else {
      version__ = nil;
    }
    signature_ = OrgBouncycastleAsn1X509AlgorithmIdentifier_getInstanceWithId_([seq getObjectAtWithInt:seqPos++]);
    issuer_ = OrgBouncycastleAsn1X500X500Name_getInstanceWithId_([seq getObjectAtWithInt:seqPos++]);
    thisUpdate_ = OrgBouncycastleAsn1X509Time_getInstanceWithId_([seq getObjectAtWithInt:seqPos++]);
    if (seqPos < [seq size] && ([[seq getObjectAtWithInt:seqPos] isKindOfClass:[OrgBouncycastleAsn1ASN1UTCTime class]] || [[seq getObjectAtWithInt:seqPos] isKindOfClass:[OrgBouncycastleAsn1ASN1GeneralizedTime class]] || [[seq getObjectAtWithInt:seqPos] isKindOfClass:[OrgBouncycastleAsn1X509Time class]])) {
      nextUpdate_ = OrgBouncycastleAsn1X509Time_getInstanceWithId_([seq getObjectAtWithInt:seqPos++]);
    }
    if (seqPos < [seq size] && !([[seq getObjectAtWithInt:seqPos] isKindOfClass:[OrgBouncycastleAsn1DERTaggedObject class]])) {
      revokedCertificates_ = OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_([seq getObjectAtWithInt:seqPos++]);
    }
    if (seqPos < [seq size] && [[seq getObjectAtWithInt:seqPos] isKindOfClass:[OrgBouncycastleAsn1DERTaggedObject class]]) {
      crlExtensions_ = OrgBouncycastleAsn1X509Extensions_getInstanceWithId_(OrgBouncycastleAsn1ASN1Sequence_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_((OrgBouncycastleAsn1ASN1TaggedObject *) check_class_cast([seq getObjectAtWithInt:seqPos], [OrgBouncycastleAsn1ASN1TaggedObject class]), YES));
    }
  }
  return self;
}

- (jint)getVersionNumber {
  if (version__ == nil) {
    return 1;
  }
  return [((JavaMathBigInteger *) nil_chk([((OrgBouncycastleAsn1ASN1Integer *) nil_chk(version__)) getValue])) intValue] + 1;
}

- (OrgBouncycastleAsn1ASN1Integer *)getVersion {
  return version__;
}

- (OrgBouncycastleAsn1X509AlgorithmIdentifier *)getSignature {
  return signature_;
}

- (OrgBouncycastleAsn1X500X500Name *)getIssuer {
  return issuer_;
}

- (OrgBouncycastleAsn1X509Time *)getThisUpdate {
  return thisUpdate_;
}

- (OrgBouncycastleAsn1X509Time *)getNextUpdate {
  return nextUpdate_;
}

- (IOSObjectArray *)getRevokedCertificates {
  if (revokedCertificates_ == nil) {
    return [IOSObjectArray newArrayWithLength:0 type:OrgBouncycastleAsn1X509TBSCertList_CRLEntry_class_()];
  }
  IOSObjectArray *entries = [IOSObjectArray newArrayWithLength:[((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(revokedCertificates_)) size] type:OrgBouncycastleAsn1X509TBSCertList_CRLEntry_class_()];
  for (jint i = 0; i < entries->size_; i++) {
    IOSObjectArray_Set(entries, i, OrgBouncycastleAsn1X509TBSCertList_CRLEntry_getInstanceWithId_([revokedCertificates_ getObjectAtWithInt:i]));
  }
  return entries;
}

- (id<JavaUtilEnumeration>)getRevokedCertificateEnumeration {
  if (revokedCertificates_ == nil) {
    return [[OrgBouncycastleAsn1X509TBSCertList_EmptyEnumeration alloc] initWithOrgBouncycastleAsn1X509TBSCertList:self];
  }
  return [[OrgBouncycastleAsn1X509TBSCertList_RevokedCertificatesEnumeration alloc] initWithOrgBouncycastleAsn1X509TBSCertList:self withJavaUtilEnumeration:[((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(revokedCertificates_)) getObjects]];
}

- (OrgBouncycastleAsn1X509Extensions *)getExtensions {
  return crlExtensions_;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  OrgBouncycastleAsn1ASN1EncodableVector *v = [[OrgBouncycastleAsn1ASN1EncodableVector alloc] init];
  if (version__ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:version__];
  }
  [v addWithOrgBouncycastleAsn1ASN1Encodable:signature_];
  [v addWithOrgBouncycastleAsn1ASN1Encodable:issuer_];
  [v addWithOrgBouncycastleAsn1ASN1Encodable:thisUpdate_];
  if (nextUpdate_ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:nextUpdate_];
  }
  if (revokedCertificates_ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:revokedCertificates_];
  }
  if (crlExtensions_ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DERTaggedObject alloc] initWithInt:0 withOrgBouncycastleAsn1ASN1Encodable:crlExtensions_]];
  }
  return [[OrgBouncycastleAsn1DERSequence alloc] initWithOrgBouncycastleAsn1ASN1EncodableVector:v];
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1X509TBSCertList *)other {
  [super copyAllFieldsTo:other];
  other->version__ = version__;
  other->signature_ = signature_;
  other->issuer_ = issuer_;
  other->thisUpdate_ = thisUpdate_;
  other->nextUpdate_ = nextUpdate_;
  other->revokedCertificates_ = revokedCertificates_;
  other->crlExtensions_ = crlExtensions_;
}

@end

OrgBouncycastleAsn1X509TBSCertList *OrgBouncycastleAsn1X509TBSCertList_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_) {
  OrgBouncycastleAsn1X509TBSCertList_init();
  return OrgBouncycastleAsn1X509TBSCertList_getInstanceWithId_(OrgBouncycastleAsn1ASN1Sequence_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(obj, explicit_));
}

OrgBouncycastleAsn1X509TBSCertList *OrgBouncycastleAsn1X509TBSCertList_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1X509TBSCertList_init();
  if ([obj isKindOfClass:[OrgBouncycastleAsn1X509TBSCertList class]]) {
    return (OrgBouncycastleAsn1X509TBSCertList *) check_class_cast(obj, [OrgBouncycastleAsn1X509TBSCertList class]);
  }
  else if (obj != nil) {
    return [[OrgBouncycastleAsn1X509TBSCertList alloc] initWithOrgBouncycastleAsn1ASN1Sequence:OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(obj)];
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509TBSCertList)

@implementation OrgBouncycastleAsn1X509TBSCertList_CRLEntry

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq {
  if (self = [super init]) {
    if ([((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) size] < 2 || [seq size] > 3) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:JreStrcat("$I", @"Bad sequence size: ", [seq size])];
    }
    self->seq_ = seq;
  }
  return self;
}

+ (OrgBouncycastleAsn1X509TBSCertList_CRLEntry *)getInstanceWithId:(id)o {
  return OrgBouncycastleAsn1X509TBSCertList_CRLEntry_getInstanceWithId_(o);
}

- (OrgBouncycastleAsn1ASN1Integer *)getUserCertificate {
  return OrgBouncycastleAsn1ASN1Integer_getInstanceWithId_([((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq_)) getObjectAtWithInt:0]);
}

- (OrgBouncycastleAsn1X509Time *)getRevocationDate {
  return OrgBouncycastleAsn1X509Time_getInstanceWithId_([((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq_)) getObjectAtWithInt:1]);
}

- (OrgBouncycastleAsn1X509Extensions *)getExtensions {
  if (crlEntryExtensions_ == nil && [((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq_)) size] == 3) {
    crlEntryExtensions_ = OrgBouncycastleAsn1X509Extensions_getInstanceWithId_([seq_ getObjectAtWithInt:2]);
  }
  return crlEntryExtensions_;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return seq_;
}

- (jboolean)hasExtensions {
  return [((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq_)) size] == 3;
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1X509TBSCertList_CRLEntry *)other {
  [super copyAllFieldsTo:other];
  other->seq_ = seq_;
  other->crlEntryExtensions_ = crlEntryExtensions_;
}

@end

OrgBouncycastleAsn1X509TBSCertList_CRLEntry *OrgBouncycastleAsn1X509TBSCertList_CRLEntry_getInstanceWithId_(id o) {
  OrgBouncycastleAsn1X509TBSCertList_CRLEntry_init();
  if ([o isKindOfClass:[OrgBouncycastleAsn1X509TBSCertList_CRLEntry class]]) {
    return ((OrgBouncycastleAsn1X509TBSCertList_CRLEntry *) check_class_cast(o, [OrgBouncycastleAsn1X509TBSCertList_CRLEntry class]));
  }
  else if (o != nil) {
    return [[OrgBouncycastleAsn1X509TBSCertList_CRLEntry alloc] initWithOrgBouncycastleAsn1ASN1Sequence:OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(o)];
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509TBSCertList_CRLEntry)

@implementation OrgBouncycastleAsn1X509TBSCertList_RevokedCertificatesEnumeration

- (instancetype)initWithOrgBouncycastleAsn1X509TBSCertList:(OrgBouncycastleAsn1X509TBSCertList *)outer$
                                   withJavaUtilEnumeration:(id<JavaUtilEnumeration>)en {
  if (self = [super init]) {
    self->en_ = en;
  }
  return self;
}

- (jboolean)hasMoreElements {
  return [((id<JavaUtilEnumeration>) nil_chk(en_)) hasMoreElements];
}

- (id)nextElement {
  return OrgBouncycastleAsn1X509TBSCertList_CRLEntry_getInstanceWithId_([((id<JavaUtilEnumeration>) nil_chk(en_)) nextElement]);
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1X509TBSCertList_RevokedCertificatesEnumeration *)other {
  [super copyAllFieldsTo:other];
  other->en_ = en_;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509TBSCertList_RevokedCertificatesEnumeration)

@implementation OrgBouncycastleAsn1X509TBSCertList_EmptyEnumeration

- (jboolean)hasMoreElements {
  return NO;
}

- (id)nextElement {
  return nil;
}

- (instancetype)initWithOrgBouncycastleAsn1X509TBSCertList:(OrgBouncycastleAsn1X509TBSCertList *)outer$ {
  return [super init];
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1X509TBSCertList_EmptyEnumeration)
