//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/modules/utils/BaseKeyValueEngine.java
//

#ifndef _ImActorModelModulesUtilsBaseKeyValueEngine_H_
#define _ImActorModelModulesUtilsBaseKeyValueEngine_H_

@class IOSByteArray;
@class IOSLongArray;
@class JavaUtilHashMap;
@protocol ImActorModelDroidkitEngineKeyValueItem;
@protocol ImActorModelDroidkitEngineKeyValueStorage;
@protocol JavaUtilList;

#include "J2ObjC_header.h"
#include "im/actor/model/droidkit/engine/KeyValueEngine.h"

@interface ImActorModelModulesUtilsBaseKeyValueEngine : NSObject < ImActorModelDroidkitEngineKeyValueEngine > {
}

- (instancetype)initWithImActorModelDroidkitEngineKeyValueStorage:(id<ImActorModelDroidkitEngineKeyValueStorage>)storage;

- (IOSByteArray *)serializeWithImActorModelDroidkitEngineKeyValueItem:(id<ImActorModelDroidkitEngineKeyValueItem>)value;

- (id)deserializeWithByteArray:(IOSByteArray *)data;

- (void)addOrUpdateItemWithImActorModelDroidkitEngineKeyValueItem:(id<ImActorModelDroidkitEngineKeyValueItem>)item;

- (void)addOrUpdateItemsWithJavaUtilList:(id<JavaUtilList>)values;

- (void)removeItemWithLong:(jlong)id_;

- (void)removeItemsWithLongArray:(IOSLongArray *)ids;

- (void)clear;

- (id)getValueWithLong:(jlong)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorModelModulesUtilsBaseKeyValueEngine)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(ImActorModelModulesUtilsBaseKeyValueEngine)

#endif // _ImActorModelModulesUtilsBaseKeyValueEngine_H_
