//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/network/parser/HeaderBserObject.java
//

#ifndef _ImActorModelNetworkParserHeaderBserObject_H_
#define _ImActorModelNetworkParserHeaderBserObject_H_

#include "J2ObjC_header.h"
#include "im/actor/model/droidkit/bser/BserObject.h"

@interface ImActorModelNetworkParserHeaderBserObject : ImActorModelDroidkitBserBserObject {
}

- (jint)getHeaderKey;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorModelNetworkParserHeaderBserObject)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(ImActorModelNetworkParserHeaderBserObject)

#endif // _ImActorModelNetworkParserHeaderBserObject_H_
