//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core/src/main/java/im/actor/model/api/rpc/RequestEditName.java
//

#ifndef _APRequestEditName_H_
#define _APRequestEditName_H_

#include "J2ObjC_header.h"
#include "im/actor/model/network/parser/Request.h"

@class BSBserValues;
@class BSBserWriter;
@class IOSByteArray;

#define APRequestEditName_HEADER 53

@interface APRequestEditName : APRequest

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)name;

+ (APRequestEditName *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (NSString *)getName;

- (void)parseWithBSBserValues:(BSBserValues *)values;

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(APRequestEditName)

J2OBJC_STATIC_FIELD_GETTER(APRequestEditName, HEADER, jint)

FOUNDATION_EXPORT APRequestEditName *APRequestEditName_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void APRequestEditName_initWithNSString_(APRequestEditName *self, NSString *name);

FOUNDATION_EXPORT APRequestEditName *new_APRequestEditName_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void APRequestEditName_init(APRequestEditName *self);

FOUNDATION_EXPORT APRequestEditName *new_APRequestEditName_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(APRequestEditName)

typedef APRequestEditName ImActorModelApiRpcRequestEditName;

#endif // _APRequestEditName_H_
