//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core/src/main/java/im/actor/model/api/rpc/RequestGetIntegrationToken.java
//


#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/model/api/OutPeer.h"
#include "im/actor/model/api/rpc/RequestGetIntegrationToken.h"
#include "im/actor/model/droidkit/bser/Bser.h"
#include "im/actor/model/droidkit/bser/BserObject.h"
#include "im/actor/model/droidkit/bser/BserValues.h"
#include "im/actor/model/droidkit/bser/BserWriter.h"
#include "im/actor/model/network/parser/Request.h"
#include "java/io/IOException.h"

@interface APRequestGetIntegrationToken () {
 @public
  APOutPeer *groupPeer_;
}

@end

J2OBJC_FIELD_SETTER(APRequestGetIntegrationToken, groupPeer_, APOutPeer *)

@implementation APRequestGetIntegrationToken

+ (APRequestGetIntegrationToken *)fromBytesWithByteArray:(IOSByteArray *)data {
  return APRequestGetIntegrationToken_fromBytesWithByteArray_(data);
}

- (instancetype)initWithAPOutPeer:(APOutPeer *)groupPeer {
  APRequestGetIntegrationToken_initWithAPOutPeer_(self, groupPeer);
  return self;
}

- (instancetype)init {
  APRequestGetIntegrationToken_init(self);
  return self;
}

- (APOutPeer *)getGroupPeer {
  return self->groupPeer_;
}

- (void)parseWithBSBserValues:(BSBserValues *)values {
  self->groupPeer_ = [((BSBserValues *) nil_chk(values)) getObjWithInt:1 withBSBserObject:new_APOutPeer_init()];
}

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer {
  if (self->groupPeer_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [((BSBserWriter *) nil_chk(writer)) writeObjectWithInt:1 withBSBserObject:self->groupPeer_];
}

- (NSString *)description {
  NSString *res = @"rpc GetIntegrationToken{";
  res = JreStrcat("$$", res, JreStrcat("$@", @"groupPeer=", self->groupPeer_));
  res = JreStrcat("$C", res, '}');
  return res;
}

- (jint)getHeaderKey {
  return APRequestGetIntegrationToken_HEADER;
}

@end

APRequestGetIntegrationToken *APRequestGetIntegrationToken_fromBytesWithByteArray_(IOSByteArray *data) {
  APRequestGetIntegrationToken_initialize();
  return ((APRequestGetIntegrationToken *) BSBser_parseWithBSBserObject_withByteArray_(new_APRequestGetIntegrationToken_init(), data));
}

void APRequestGetIntegrationToken_initWithAPOutPeer_(APRequestGetIntegrationToken *self, APOutPeer *groupPeer) {
  (void) APRequest_init(self);
  self->groupPeer_ = groupPeer;
}

APRequestGetIntegrationToken *new_APRequestGetIntegrationToken_initWithAPOutPeer_(APOutPeer *groupPeer) {
  APRequestGetIntegrationToken *self = [APRequestGetIntegrationToken alloc];
  APRequestGetIntegrationToken_initWithAPOutPeer_(self, groupPeer);
  return self;
}

void APRequestGetIntegrationToken_init(APRequestGetIntegrationToken *self) {
  (void) APRequest_init(self);
}

APRequestGetIntegrationToken *new_APRequestGetIntegrationToken_init() {
  APRequestGetIntegrationToken *self = [APRequestGetIntegrationToken alloc];
  APRequestGetIntegrationToken_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(APRequestGetIntegrationToken)
