package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.core.network.parser.*;

import org.jetbrains.annotations.NotNull;

import java.io.IOException;

public class ResponseStartPhoneAuth extends Response {

    public static final int HEADER = 0xc1;
    public static ResponseStartPhoneAuth fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseStartPhoneAuth(), data);
    }

    private String transactionHash;
    private boolean isRegistered;

    public ResponseStartPhoneAuth(@NotNull String transactionHash, boolean isRegistered) {
        this.transactionHash = transactionHash;
        this.isRegistered = isRegistered;
    }

    public ResponseStartPhoneAuth() {

    }

    @NotNull
    public String getTransactionHash() {
        return this.transactionHash;
    }

    public boolean isRegistered() {
        return this.isRegistered;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.transactionHash = values.getString(1);
        this.isRegistered = values.getBool(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.transactionHash == null) {
            throw new IOException();
        }
        writer.writeString(1, this.transactionHash);
        writer.writeBool(2, this.isRegistered);
    }

    @Override
    public String toString() {
        String res = "tuple StartPhoneAuth{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
