//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/crypto/asn1/ASN1Null.java
//

#ifndef _ImActorModelCryptoAsn1ASN1Null_H_
#define _ImActorModelCryptoAsn1ASN1Null_H_

@class BSDataOutput;

#include "J2ObjC_header.h"
#include "im/actor/model/crypto/asn1/ASN1Primitive.h"

@interface ImActorModelCryptoAsn1ASN1Null : ImActorModelCryptoAsn1ASN1Primitive {
}

- (void)serializeWithBSDataOutput:(BSDataOutput *)dataOutput;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorModelCryptoAsn1ASN1Null)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(ImActorModelCryptoAsn1ASN1Null)

#endif // _ImActorModelCryptoAsn1ASN1Null_H_
