//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/com/droidkit/actors/messages/DeadLetter.java
//

#include "J2ObjC_source.h"
#include "com/droidkit/actors/messages/DeadLetter.h"

@interface ComDroidkitActorsMessagesDeadLetter () {
 @public
  id message_;
}
@end

J2OBJC_FIELD_SETTER(ComDroidkitActorsMessagesDeadLetter, message_, id)

@implementation ComDroidkitActorsMessagesDeadLetter

- (instancetype)initWithId:(id)message {
  if (self = [super init]) {
    ComDroidkitActorsMessagesDeadLetter_set_message_(self, message);
  }
  return self;
}

- (id)getMessage {
  return message_;
}

- (NSString *)description {
  return JreStrcat("$@C", @"DeadLetter(", message_, ')');
}

- (void)dealloc {
  RELEASE_(message_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ComDroidkitActorsMessagesDeadLetter *)other {
  [super copyAllFieldsTo:other];
  ComDroidkitActorsMessagesDeadLetter_set_message_(other, message_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithId:", "DeadLetter", NULL, 0x1, NULL },
    { "getMessage", NULL, "Ljava.lang.Object;", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "message_", NULL, 0x2, "Ljava.lang.Object;", NULL,  },
  };
  static const J2ObjcClassInfo _ComDroidkitActorsMessagesDeadLetter = { 1, "DeadLetter", "com.droidkit.actors.messages", NULL, 0x1, 3, methods, 1, fields, 0, NULL};
  return &_ComDroidkitActorsMessagesDeadLetter;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComDroidkitActorsMessagesDeadLetter)
