package im.actor.model.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.model.droidkit.bser.Bser;
import im.actor.model.droidkit.bser.BserValues;
import im.actor.model.droidkit.bser.BserWriter;

import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import im.actor.model.network.parser.*;

public class RequestInitLlectro extends Request<ResponseVoid> {

    public static final int HEADER = 0xa3;
    public static RequestInitLlectro fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestInitLlectro(), data);
    }

    private int screenWidth;
    private int screenHeight;

    public RequestInitLlectro(int screenWidth, int screenHeight) {
        this.screenWidth = screenWidth;
        this.screenHeight = screenHeight;
    }

    public RequestInitLlectro() {

    }

    public int getScreenWidth() {
        return this.screenWidth;
    }

    public int getScreenHeight() {
        return this.screenHeight;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.screenWidth = values.getInt(1);
        this.screenHeight = values.getInt(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeInt(1, this.screenWidth);
        writer.writeInt(2, this.screenHeight);
    }

    @Override
    public String toString() {
        String res = "rpc InitLlectro{";
        res += "screenWidth=" + this.screenWidth;
        res += ", screenHeight=" + this.screenHeight;
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
