//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/tsp/TimeStampReq.java
//

#include "J2ObjC_source.h"
#include "org/bouncycastle/asn1/ASN1Boolean.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1EncodableVector.h"
#include "org/bouncycastle/asn1/ASN1Integer.h"
#include "org/bouncycastle/asn1/ASN1ObjectIdentifier.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/ASN1TaggedObject.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/DERTaggedObject.h"
#include "org/bouncycastle/asn1/tsp/MessageImprint.h"
#include "org/bouncycastle/asn1/tsp/TimeStampReq.h"
#include "org/bouncycastle/asn1/x509/Extensions.h"

@interface OrgBouncycastleAsn1TspTimeStampReq ()
- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq;
@end

@implementation OrgBouncycastleAsn1TspTimeStampReq

+ (OrgBouncycastleAsn1TspTimeStampReq *)getInstanceWithId:(id)o {
  return OrgBouncycastleAsn1TspTimeStampReq_getInstanceWithId_(o);
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq {
  if (self = [super init]) {
    jint nbObjects = [((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) size];
    jint seqStart = 0;
    version__ = OrgBouncycastleAsn1ASN1Integer_getInstanceWithId_([seq getObjectAtWithInt:seqStart]);
    seqStart++;
    messageImprint_ = OrgBouncycastleAsn1TspMessageImprint_getInstanceWithId_([seq getObjectAtWithInt:seqStart]);
    seqStart++;
    for (jint opt = seqStart; opt < nbObjects; opt++) {
      if ([[seq getObjectAtWithInt:opt] isKindOfClass:[OrgBouncycastleAsn1ASN1ObjectIdentifier class]]) {
        tsaPolicy_ = OrgBouncycastleAsn1ASN1ObjectIdentifier_getInstanceWithId_([seq getObjectAtWithInt:opt]);
      }
      else if ([[seq getObjectAtWithInt:opt] isKindOfClass:[OrgBouncycastleAsn1ASN1Integer class]]) {
        nonce_ = OrgBouncycastleAsn1ASN1Integer_getInstanceWithId_([seq getObjectAtWithInt:opt]);
      }
      else if ([[seq getObjectAtWithInt:opt] isKindOfClass:[OrgBouncycastleAsn1ASN1Boolean class]]) {
        certReq_ = OrgBouncycastleAsn1ASN1Boolean_getInstanceWithId_([seq getObjectAtWithInt:opt]);
      }
      else if ([[seq getObjectAtWithInt:opt] isKindOfClass:[OrgBouncycastleAsn1ASN1TaggedObject class]]) {
        OrgBouncycastleAsn1ASN1TaggedObject *tagged = (OrgBouncycastleAsn1ASN1TaggedObject *) check_class_cast([seq getObjectAtWithInt:opt], [OrgBouncycastleAsn1ASN1TaggedObject class]);
        if ([((OrgBouncycastleAsn1ASN1TaggedObject *) nil_chk(tagged)) getTagNo] == 0) {
          extensions_ = OrgBouncycastleAsn1X509Extensions_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(tagged, NO);
        }
      }
    }
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1TspMessageImprint:(OrgBouncycastleAsn1TspMessageImprint *)messageImprint
                 withOrgBouncycastleAsn1ASN1ObjectIdentifier:(OrgBouncycastleAsn1ASN1ObjectIdentifier *)tsaPolicy
                          withOrgBouncycastleAsn1ASN1Integer:(OrgBouncycastleAsn1ASN1Integer *)nonce
                          withOrgBouncycastleAsn1ASN1Boolean:(OrgBouncycastleAsn1ASN1Boolean *)certReq
                       withOrgBouncycastleAsn1X509Extensions:(OrgBouncycastleAsn1X509Extensions *)extensions {
  if (self = [super init]) {
    version__ = [[OrgBouncycastleAsn1ASN1Integer alloc] initWithLong:1];
    self->messageImprint_ = messageImprint;
    self->tsaPolicy_ = tsaPolicy;
    self->nonce_ = nonce;
    self->certReq_ = certReq;
    self->extensions_ = extensions;
  }
  return self;
}

- (OrgBouncycastleAsn1ASN1Integer *)getVersion {
  return version__;
}

- (OrgBouncycastleAsn1TspMessageImprint *)getMessageImprint {
  return messageImprint_;
}

- (OrgBouncycastleAsn1ASN1ObjectIdentifier *)getReqPolicy {
  return tsaPolicy_;
}

- (OrgBouncycastleAsn1ASN1Integer *)getNonce {
  return nonce_;
}

- (OrgBouncycastleAsn1ASN1Boolean *)getCertReq {
  return certReq_;
}

- (OrgBouncycastleAsn1X509Extensions *)getExtensions {
  return extensions_;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  OrgBouncycastleAsn1ASN1EncodableVector *v = [[OrgBouncycastleAsn1ASN1EncodableVector alloc] init];
  [v addWithOrgBouncycastleAsn1ASN1Encodable:version__];
  [v addWithOrgBouncycastleAsn1ASN1Encodable:messageImprint_];
  if (tsaPolicy_ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:tsaPolicy_];
  }
  if (nonce_ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:nonce_];
  }
  if (certReq_ != nil && [certReq_ isTrue]) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:certReq_];
  }
  if (extensions_ != nil) {
    [v addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DERTaggedObject alloc] initWithBoolean:NO withInt:0 withOrgBouncycastleAsn1ASN1Encodable:extensions_]];
  }
  return [[OrgBouncycastleAsn1DERSequence alloc] initWithOrgBouncycastleAsn1ASN1EncodableVector:v];
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1TspTimeStampReq *)other {
  [super copyAllFieldsTo:other];
  other->version__ = version__;
  other->messageImprint_ = messageImprint_;
  other->tsaPolicy_ = tsaPolicy_;
  other->nonce_ = nonce_;
  other->certReq_ = certReq_;
  other->extensions_ = extensions_;
}

@end

OrgBouncycastleAsn1TspTimeStampReq *OrgBouncycastleAsn1TspTimeStampReq_getInstanceWithId_(id o) {
  OrgBouncycastleAsn1TspTimeStampReq_init();
  if ([o isKindOfClass:[OrgBouncycastleAsn1TspTimeStampReq class]]) {
    return (OrgBouncycastleAsn1TspTimeStampReq *) check_class_cast(o, [OrgBouncycastleAsn1TspTimeStampReq class]);
  }
  else if (o != nil) {
    return [[OrgBouncycastleAsn1TspTimeStampReq alloc] initWithOrgBouncycastleAsn1ASN1Sequence:OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(o)];
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1TspTimeStampReq)
