//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/core-crypto/src/main/java/org/bouncycastle/math/ec/ECPointMap.java
//


#include "J2ObjC_source.h"
#include "org/bouncycastle/math/ec/ECPoint.h"
#include "org/bouncycastle/math/ec/ECPointMap.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcECPointMap)
