package im.actor.model.api.updates;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.model.droidkit.bser.Bser;
import im.actor.model.droidkit.bser.BserParser;
import im.actor.model.droidkit.bser.BserObject;
import im.actor.model.droidkit.bser.BserValues;
import im.actor.model.droidkit.bser.BserWriter;
import im.actor.model.droidkit.bser.DataInput;
import im.actor.model.droidkit.bser.DataOutput;
import im.actor.model.droidkit.bser.util.SparseArray;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import static im.actor.model.droidkit.bser.Utils.*;
import java.io.IOException;
import im.actor.model.network.parser.*;
import java.util.List;
import java.util.ArrayList;
import im.actor.model.api.*;

public class UpdateCallEnd extends Update {

    public static final int HEADER = 0x53;
    public static UpdateCallEnd fromBytes(byte[] data) throws IOException {
        return Bser.parse(new UpdateCallEnd(), data);
    }

    private String callId;

    public UpdateCallEnd(@NotNull String callId) {
        this.callId = callId;
    }

    public UpdateCallEnd() {

    }

    @NotNull
    public String getCallId() {
        return this.callId;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.callId = values.getString(2);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.callId == null) {
            throw new IOException();
        }
        writer.writeString(2, this.callId);
    }

    @Override
    public String toString() {
        String res = "update CallEnd{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
