//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/com/droidkit/actors/ActorRef.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/droidkit/actors/ActorRef.h"
#include "com/droidkit/actors/ActorSystem.h"
#include "com/droidkit/actors/ActorTime.h"
#include "com/droidkit/actors/mailbox/ActorDispatcher.h"
#include "com/droidkit/actors/mailbox/ActorEndpoint.h"
#include "java/util/UUID.h"

@interface DAActorRef () {
 @public
  DAActorSystem *system__;
  ComDroidkitActorsMailboxActorDispatcher *dispatcher_;
  JavaUtilUUID *uuid_;
  NSString *path_;
  ComDroidkitActorsMailboxActorEndpoint *endpoint_;
}
@end

J2OBJC_FIELD_SETTER(DAActorRef, system__, DAActorSystem *)
J2OBJC_FIELD_SETTER(DAActorRef, dispatcher_, ComDroidkitActorsMailboxActorDispatcher *)
J2OBJC_FIELD_SETTER(DAActorRef, uuid_, JavaUtilUUID *)
J2OBJC_FIELD_SETTER(DAActorRef, path_, NSString *)
J2OBJC_FIELD_SETTER(DAActorRef, endpoint_, ComDroidkitActorsMailboxActorEndpoint *)

@implementation DAActorRef

- (JavaUtilUUID *)getUuid {
  return uuid_;
}

- (NSString *)getPath {
  return path_;
}

- (DAActorSystem *)system {
  return system__;
}

- (instancetype)initWithComDroidkitActorsMailboxActorEndpoint:(ComDroidkitActorsMailboxActorEndpoint *)endpoint
                                            withDAActorSystem:(DAActorSystem *)system
                  withComDroidkitActorsMailboxActorDispatcher:(ComDroidkitActorsMailboxActorDispatcher *)dispatcher
                                             withJavaUtilUUID:(JavaUtilUUID *)uuid
                                                 withNSString:(NSString *)path {
  if (self = [super init]) {
    DAActorRef_set_endpoint_(self, endpoint);
    DAActorRef_set_system__(self, system);
    DAActorRef_set_dispatcher_(self, dispatcher);
    DAActorRef_set_uuid_(self, uuid);
    DAActorRef_set_path_(self, path);
  }
  return self;
}

- (void)sendWithId:(id)message {
  [self sendWithId:message withDAActorRef:nil];
}

- (void)sendWithId:(id)message
    withDAActorRef:(DAActorRef *)sender {
  [self sendWithId:message withLong:0 withDAActorRef:sender];
}

- (void)sendWithId:(id)message
          withLong:(jlong)delay {
  [self sendWithId:message withLong:delay withDAActorRef:nil];
}

- (void)sendWithId:(id)message
          withLong:(jlong)delay
    withDAActorRef:(DAActorRef *)sender {
  [((ComDroidkitActorsMailboxActorDispatcher *) nil_chk(dispatcher_)) sendMessageWithComDroidkitActorsMailboxActorEndpoint:endpoint_ withId:message withLong:DAActorTime_currentTime() + delay withDAActorRef:sender];
}

- (void)sendOnceWithId:(id)message {
  [self sendWithId:message withDAActorRef:nil];
}

- (void)sendOnceWithId:(id)message
        withDAActorRef:(DAActorRef *)sender {
  [self sendOnceWithId:message withLong:0 withDAActorRef:sender];
}

- (void)sendOnceWithId:(id)message
              withLong:(jlong)delay {
  [self sendOnceWithId:message withLong:delay withDAActorRef:nil];
}

- (void)sendOnceWithId:(id)message
              withLong:(jlong)delay
        withDAActorRef:(DAActorRef *)sender {
  [((ComDroidkitActorsMailboxActorDispatcher *) nil_chk(dispatcher_)) sendMessageOnceWithComDroidkitActorsMailboxActorEndpoint:endpoint_ withId:message withLong:DAActorTime_currentTime() + delay withDAActorRef:sender];
}

- (void)dealloc {
  RELEASE_(system__);
  RELEASE_(dispatcher_);
  RELEASE_(uuid_);
  RELEASE_(path_);
  RELEASE_(endpoint_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(DAActorRef *)other {
  [super copyAllFieldsTo:other];
  DAActorRef_set_system__(other, system__);
  DAActorRef_set_dispatcher_(other, dispatcher_);
  DAActorRef_set_uuid_(other, uuid_);
  DAActorRef_set_path_(other, path_);
  DAActorRef_set_endpoint_(other, endpoint_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getUuid", NULL, "Ljava.util.UUID;", 0x1, NULL },
    { "getPath", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "system", NULL, "Lcom.droidkit.actors.ActorSystem;", 0x1, NULL },
    { "initWithComDroidkitActorsMailboxActorEndpoint:withDAActorSystem:withComDroidkitActorsMailboxActorDispatcher:withJavaUtilUUID:withNSString:", "ActorRef", NULL, 0x1, NULL },
    { "sendWithId:", "send", "V", 0x1, NULL },
    { "sendWithId:withDAActorRef:", "send", "V", 0x1, NULL },
    { "sendWithId:withLong:", "send", "V", 0x1, NULL },
    { "sendWithId:withLong:withDAActorRef:", "send", "V", 0x1, NULL },
    { "sendOnceWithId:", "sendOnce", "V", 0x1, NULL },
    { "sendOnceWithId:withDAActorRef:", "sendOnce", "V", 0x1, NULL },
    { "sendOnceWithId:withLong:", "sendOnce", "V", 0x1, NULL },
    { "sendOnceWithId:withLong:withDAActorRef:", "sendOnce", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "system__", "system", 0x2, "Lcom.droidkit.actors.ActorSystem;", NULL,  },
    { "dispatcher_", NULL, 0x2, "Lcom.droidkit.actors.mailbox.ActorDispatcher;", NULL,  },
    { "uuid_", NULL, 0x2, "Ljava.util.UUID;", NULL,  },
    { "path_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "endpoint_", NULL, 0x2, "Lcom.droidkit.actors.mailbox.ActorEndpoint;", NULL,  },
  };
  static const J2ObjcClassInfo _DAActorRef = { 1, "ActorRef", "com.droidkit.actors", NULL, 0x1, 12, methods, 5, fields, 0, NULL};
  return &_DAActorRef;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DAActorRef)
