//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/ASN1OutputStream.java
//

#ifndef _OrgBouncycastleAsn1ASN1OutputStream_H_
#define _OrgBouncycastleAsn1ASN1OutputStream_H_

@class IOSByteArray;
@class JavaIoOutputStream;
@class OrgBouncycastleAsn1ASN1Primitive;
@protocol OrgBouncycastleAsn1ASN1Encodable;

#include "J2ObjC_header.h"

@interface OrgBouncycastleAsn1ASN1OutputStream : NSObject {
}

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os;

- (void)writeLengthWithInt:(jint)length;

- (void)writeWithInt:(jint)b;

- (void)writeWithByteArray:(IOSByteArray *)bytes;

- (void)writeWithByteArray:(IOSByteArray *)bytes
                   withInt:(jint)off
                   withInt:(jint)len;

- (void)writeEncodedWithInt:(jint)tag
              withByteArray:(IOSByteArray *)bytes;

- (void)writeTagWithInt:(jint)flags
                withInt:(jint)tagNo;

- (void)writeEncodedWithInt:(jint)flags
                    withInt:(jint)tagNo
              withByteArray:(IOSByteArray *)bytes;

- (void)writeNull;

- (void)writeObjectWithOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj;

- (void)writeImplicitObjectWithOrgBouncycastleAsn1ASN1Primitive:(OrgBouncycastleAsn1ASN1Primitive *)obj;

- (void)close;

- (void)flush;

- (OrgBouncycastleAsn1ASN1OutputStream *)getDERSubStream;

- (OrgBouncycastleAsn1ASN1OutputStream *)getDLSubStream;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1ASN1OutputStream)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1ASN1OutputStream)

@interface OrgBouncycastleAsn1ASN1OutputStream_ImplicitOutputStream : OrgBouncycastleAsn1ASN1OutputStream {
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1OutputStream:(OrgBouncycastleAsn1ASN1OutputStream *)outer$
                                     withJavaIoOutputStream:(JavaIoOutputStream *)os;

- (void)writeWithInt:(jint)b;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1ASN1OutputStream_ImplicitOutputStream)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1ASN1OutputStream_ImplicitOutputStream)

#endif // _OrgBouncycastleAsn1ASN1OutputStream_H_
