package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.runtime.collections.*;
import static im.actor.runtime.bser.Utils.*;
import im.actor.core.network.parser.*;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import com.google.j2objc.annotations.ObjectiveCName;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import im.actor.core.api.*;

public class ResponseRawRequest extends Response {

    public static final int HEADER = 0xa0a;
    public static ResponseRawRequest fromBytes(byte[] data) throws IOException {
        return Bser.parse(new ResponseRawRequest(), data);
    }

    private ApiRawValue result;

    public ResponseRawRequest(@NotNull ApiRawValue result) {
        this.result = result;
    }

    public ResponseRawRequest() {

    }

    @NotNull
    public ApiRawValue getResult() {
        return this.result;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.result = ApiRawValue.fromBytes(values.getBytes(1));
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.result == null) {
            throw new IOException();
        }

        writer.writeBytes(1, this.result.buildContainer());
    }

    @Override
    public String toString() {
        String res = "tuple RawRequest{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
