//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/droidkit/actors/mailbox/ActorDispatcher.java
//

#ifndef _DKActorDispatcher_H_
#define _DKActorDispatcher_H_

@class DKAbstractDispatcher;
@class DKActorEndpoint;
@class DKActorRef;
@class DKActorScope;
@class DKActorSystem;
@class DKEnvelope;
@class DKProps;
@class JavaUtilHashMap;

#include "J2ObjC_header.h"

@interface DKActorDispatcher : NSObject {
}

- (instancetype)initWithNSString:(NSString *)name
               withDKActorSystem:(DKActorSystem *)actorSystem;

- (void)initDispatcherWithDKAbstractDispatcher:(DKAbstractDispatcher *)dispatcher OBJC_METHOD_FAMILY_NONE;

- (DKActorRef *)referenceActorWithNSString:(NSString *)path
                               withDKProps:(DKProps *)props;

- (void)killGracefullyWithDKActorScope:(DKActorScope *)scope;

- (void)sendMessageWithDKActorEndpoint:(DKActorEndpoint *)endpoint
                                withId:(id)message
                              withLong:(jlong)time
                        withDKActorRef:(DKActorRef *)sender;

- (void)sendMessageOnceWithDKActorEndpoint:(DKActorEndpoint *)endpoint
                                    withId:(id)message
                                  withLong:(jlong)time
                            withDKActorRef:(DKActorRef *)sender;

- (void)cancelSendWithDKActorEndpoint:(DKActorEndpoint *)endpoint
                               withId:(id)message
                       withDKActorRef:(DKActorRef *)sender;

- (NSString *)getName;

- (void)processEnvelopeWithDKEnvelope:(DKEnvelope *)envelope;

@end

J2OBJC_EMPTY_STATIC_INIT(DKActorDispatcher)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef DKActorDispatcher ImActorModelDroidkitActorsMailboxActorDispatcher;

J2OBJC_TYPE_LITERAL_HEADER(DKActorDispatcher)

#endif // _DKActorDispatcher_H_
