//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/cmp/PKIHeader.java
//

#ifndef _OrgBouncycastleAsn1CmpPKIHeader_H_
#define _OrgBouncycastleAsn1CmpPKIHeader_H_

@class IOSObjectArray;
@class OrgBouncycastleAsn1ASN1EncodableVector;
@class OrgBouncycastleAsn1ASN1GeneralizedTime;
@class OrgBouncycastleAsn1ASN1Integer;
@class OrgBouncycastleAsn1ASN1OctetString;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Sequence;
@class OrgBouncycastleAsn1CmpPKIFreeText;
@class OrgBouncycastleAsn1X509AlgorithmIdentifier;
@class OrgBouncycastleAsn1X509GeneralName;
@protocol OrgBouncycastleAsn1ASN1Encodable;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

#define OrgBouncycastleAsn1CmpPKIHeader_CMP_1999 1
#define OrgBouncycastleAsn1CmpPKIHeader_CMP_2000 2

@interface OrgBouncycastleAsn1CmpPKIHeader : OrgBouncycastleAsn1ASN1Object {
}

+ (OrgBouncycastleAsn1CmpPKIHeader *)getInstanceWithId:(id)o;

- (instancetype)initWithInt:(jint)pvno
withOrgBouncycastleAsn1X509GeneralName:(OrgBouncycastleAsn1X509GeneralName *)sender
withOrgBouncycastleAsn1X509GeneralName:(OrgBouncycastleAsn1X509GeneralName *)recipient;

- (OrgBouncycastleAsn1ASN1Integer *)getPvno;

- (OrgBouncycastleAsn1X509GeneralName *)getSender;

- (OrgBouncycastleAsn1X509GeneralName *)getRecipient;

- (OrgBouncycastleAsn1ASN1GeneralizedTime *)getMessageTime;

- (OrgBouncycastleAsn1X509AlgorithmIdentifier *)getProtectionAlg;

- (OrgBouncycastleAsn1ASN1OctetString *)getSenderKID;

- (OrgBouncycastleAsn1ASN1OctetString *)getRecipKID;

- (OrgBouncycastleAsn1ASN1OctetString *)getTransactionID;

- (OrgBouncycastleAsn1ASN1OctetString *)getSenderNonce;

- (OrgBouncycastleAsn1ASN1OctetString *)getRecipNonce;

- (OrgBouncycastleAsn1CmpPKIFreeText *)getFreeText;

- (IOSObjectArray *)getGeneralInfo;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

@end

FOUNDATION_EXPORT BOOL OrgBouncycastleAsn1CmpPKIHeader_initialized;
J2OBJC_STATIC_INIT(OrgBouncycastleAsn1CmpPKIHeader)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1CmpPKIHeader *OrgBouncycastleAsn1CmpPKIHeader_getInstanceWithId_(id o);

FOUNDATION_EXPORT OrgBouncycastleAsn1X509GeneralName *OrgBouncycastleAsn1CmpPKIHeader_NULL_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgBouncycastleAsn1CmpPKIHeader, NULL_NAME_, OrgBouncycastleAsn1X509GeneralName *)

J2OBJC_STATIC_FIELD_GETTER(OrgBouncycastleAsn1CmpPKIHeader, CMP_1999, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgBouncycastleAsn1CmpPKIHeader, CMP_2000, jint)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1CmpPKIHeader)

#endif // _OrgBouncycastleAsn1CmpPKIHeader_H_
