//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/cmp/POPODecKeyRespContent.java
//

#ifndef _OrgBouncycastleAsn1CmpPOPODecKeyRespContent_H_
#define _OrgBouncycastleAsn1CmpPOPODecKeyRespContent_H_

@class IOSObjectArray;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Sequence;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

@interface OrgBouncycastleAsn1CmpPOPODecKeyRespContent : OrgBouncycastleAsn1ASN1Object {
}

+ (OrgBouncycastleAsn1CmpPOPODecKeyRespContent *)getInstanceWithId:(id)o;

- (IOSObjectArray *)toASN1IntegerArray;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1CmpPOPODecKeyRespContent)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1CmpPOPODecKeyRespContent *OrgBouncycastleAsn1CmpPOPODecKeyRespContent_getInstanceWithId_(id o);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1CmpPOPODecKeyRespContent)

#endif // _OrgBouncycastleAsn1CmpPOPODecKeyRespContent_H_
