//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/cmp/RevRepContentBuilder.java
//

#ifndef _OrgBouncycastleAsn1CmpRevRepContentBuilder_H_
#define _OrgBouncycastleAsn1CmpRevRepContentBuilder_H_

@class OrgBouncycastleAsn1ASN1EncodableVector;
@class OrgBouncycastleAsn1CmpPKIStatusInfo;
@class OrgBouncycastleAsn1CmpRevRepContent;
@class OrgBouncycastleAsn1CrmfCertId;
@class OrgBouncycastleAsn1X509CertificateList;

#include "J2ObjC_header.h"

@interface OrgBouncycastleAsn1CmpRevRepContentBuilder : NSObject {
}

- (OrgBouncycastleAsn1CmpRevRepContentBuilder *)addWithOrgBouncycastleAsn1CmpPKIStatusInfo:(OrgBouncycastleAsn1CmpPKIStatusInfo *)status;

- (OrgBouncycastleAsn1CmpRevRepContentBuilder *)addWithOrgBouncycastleAsn1CmpPKIStatusInfo:(OrgBouncycastleAsn1CmpPKIStatusInfo *)status
                                                         withOrgBouncycastleAsn1CrmfCertId:(OrgBouncycastleAsn1CrmfCertId *)certId;

- (OrgBouncycastleAsn1CmpRevRepContentBuilder *)addCrlWithOrgBouncycastleAsn1X509CertificateList:(OrgBouncycastleAsn1X509CertificateList *)crl;

- (OrgBouncycastleAsn1CmpRevRepContent *)build;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1CmpRevRepContentBuilder)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1CmpRevRepContentBuilder)

#endif // _OrgBouncycastleAsn1CmpRevRepContentBuilder_H_
