//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/crypto/RsaEncryptCipher.java
//

#ifndef _AMRsaEncryptCipher_H_
#define _AMRsaEncryptCipher_H_

@class IOSByteArray;

#include "J2ObjC_header.h"

@protocol AMRsaEncryptCipher < NSObject, JavaObject >

- (IOSByteArray *)encryptWithByteArray:(IOSByteArray *)sourceData;

@end

J2OBJC_EMPTY_STATIC_INIT(AMRsaEncryptCipher)

#define ImActorModelCryptoRsaEncryptCipher AMRsaEncryptCipher

J2OBJC_TYPE_LITERAL_HEADER(AMRsaEncryptCipher)

#endif // _AMRsaEncryptCipher_H_
