//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/crmf/CertTemplateBuilder.java
//

#include "J2ObjC_source.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1EncodableVector.h"
#include "org/bouncycastle/asn1/ASN1Integer.h"
#include "org/bouncycastle/asn1/DERBitString.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/DERTaggedObject.h"
#include "org/bouncycastle/asn1/crmf/CertTemplate.h"
#include "org/bouncycastle/asn1/crmf/CertTemplateBuilder.h"
#include "org/bouncycastle/asn1/crmf/OptionalValidity.h"
#include "org/bouncycastle/asn1/x500/X500Name.h"
#include "org/bouncycastle/asn1/x509/AlgorithmIdentifier.h"
#include "org/bouncycastle/asn1/x509/Extensions.h"
#include "org/bouncycastle/asn1/x509/SubjectPublicKeyInfo.h"
#include "org/bouncycastle/asn1/x509/X509Extensions.h"

__attribute__((unused)) static void OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1CrmfCertTemplateBuilder *self, OrgBouncycastleAsn1ASN1EncodableVector *v, jint tagNo, jboolean isExplicit, id<OrgBouncycastleAsn1ASN1Encodable> obj);

@interface OrgBouncycastleAsn1CrmfCertTemplateBuilder () {
 @public
  OrgBouncycastleAsn1ASN1Integer *version__;
  OrgBouncycastleAsn1ASN1Integer *serialNumber_;
  OrgBouncycastleAsn1X509AlgorithmIdentifier *signingAlg_;
  OrgBouncycastleAsn1X500X500Name *issuer_;
  OrgBouncycastleAsn1CrmfOptionalValidity *validity_;
  OrgBouncycastleAsn1X500X500Name *subject_;
  OrgBouncycastleAsn1X509SubjectPublicKeyInfo *publicKey_;
  OrgBouncycastleAsn1DERBitString *issuerUID_;
  OrgBouncycastleAsn1DERBitString *subjectUID_;
  OrgBouncycastleAsn1X509Extensions *extensions_;
}

- (void)addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector:(OrgBouncycastleAsn1ASN1EncodableVector *)v
                                                      withInt:(jint)tagNo
                                                  withBoolean:(jboolean)isExplicit
                         withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj;
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, version__, OrgBouncycastleAsn1ASN1Integer *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, serialNumber_, OrgBouncycastleAsn1ASN1Integer *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, signingAlg_, OrgBouncycastleAsn1X509AlgorithmIdentifier *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, issuer_, OrgBouncycastleAsn1X500X500Name *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, validity_, OrgBouncycastleAsn1CrmfOptionalValidity *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, subject_, OrgBouncycastleAsn1X500X500Name *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, publicKey_, OrgBouncycastleAsn1X509SubjectPublicKeyInfo *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, issuerUID_, OrgBouncycastleAsn1DERBitString *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, subjectUID_, OrgBouncycastleAsn1DERBitString *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CrmfCertTemplateBuilder, extensions_, OrgBouncycastleAsn1X509Extensions *)

@implementation OrgBouncycastleAsn1CrmfCertTemplateBuilder

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setVersionWithInt:(jint)ver {
  version__ = [[OrgBouncycastleAsn1ASN1Integer alloc] initWithLong:ver];
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setSerialNumberWithOrgBouncycastleAsn1ASN1Integer:(OrgBouncycastleAsn1ASN1Integer *)ser {
  serialNumber_ = ser;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setSigningAlgWithOrgBouncycastleAsn1X509AlgorithmIdentifier:(OrgBouncycastleAsn1X509AlgorithmIdentifier *)aid {
  signingAlg_ = aid;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setIssuerWithOrgBouncycastleAsn1X500X500Name:(OrgBouncycastleAsn1X500X500Name *)name {
  issuer_ = name;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setValidityWithOrgBouncycastleAsn1CrmfOptionalValidity:(OrgBouncycastleAsn1CrmfOptionalValidity *)v {
  validity_ = v;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setSubjectWithOrgBouncycastleAsn1X500X500Name:(OrgBouncycastleAsn1X500X500Name *)name {
  subject_ = name;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setPublicKeyWithOrgBouncycastleAsn1X509SubjectPublicKeyInfo:(OrgBouncycastleAsn1X509SubjectPublicKeyInfo *)spki {
  publicKey_ = spki;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setIssuerUIDWithOrgBouncycastleAsn1DERBitString:(OrgBouncycastleAsn1DERBitString *)uid {
  issuerUID_ = uid;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setSubjectUIDWithOrgBouncycastleAsn1DERBitString:(OrgBouncycastleAsn1DERBitString *)uid {
  subjectUID_ = uid;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setExtensionsWithOrgBouncycastleAsn1X509X509Extensions:(OrgBouncycastleAsn1X509X509Extensions *)extens {
  return [self setExtensionsWithOrgBouncycastleAsn1X509Extensions:OrgBouncycastleAsn1X509Extensions_getInstanceWithId_(extens)];
}

- (OrgBouncycastleAsn1CrmfCertTemplateBuilder *)setExtensionsWithOrgBouncycastleAsn1X509Extensions:(OrgBouncycastleAsn1X509Extensions *)extens {
  extensions_ = extens;
  return self;
}

- (OrgBouncycastleAsn1CrmfCertTemplate *)build {
  OrgBouncycastleAsn1ASN1EncodableVector *v = [[OrgBouncycastleAsn1ASN1EncodableVector alloc] init];
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 0, NO, version__);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 1, NO, serialNumber_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 2, NO, signingAlg_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 3, YES, issuer_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 4, NO, validity_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 5, YES, subject_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 6, NO, publicKey_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 7, NO, issuerUID_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 8, NO, subjectUID_);
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, 9, NO, extensions_);
  return OrgBouncycastleAsn1CrmfCertTemplate_getInstanceWithId_([[OrgBouncycastleAsn1DERSequence alloc] initWithOrgBouncycastleAsn1ASN1EncodableVector:v]);
}

- (void)addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector:(OrgBouncycastleAsn1ASN1EncodableVector *)v
                                                      withInt:(jint)tagNo
                                                  withBoolean:(jboolean)isExplicit
                         withOrgBouncycastleAsn1ASN1Encodable:(id<OrgBouncycastleAsn1ASN1Encodable>)obj {
  OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(self, v, tagNo, isExplicit, obj);
}

- (instancetype)init {
  return [super init];
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1CrmfCertTemplateBuilder *)other {
  [super copyAllFieldsTo:other];
  other->version__ = version__;
  other->serialNumber_ = serialNumber_;
  other->signingAlg_ = signingAlg_;
  other->issuer_ = issuer_;
  other->validity_ = validity_;
  other->subject_ = subject_;
  other->publicKey_ = publicKey_;
  other->issuerUID_ = issuerUID_;
  other->subjectUID_ = subjectUID_;
  other->extensions_ = extensions_;
}

@end

void OrgBouncycastleAsn1CrmfCertTemplateBuilder_addOptionalWithOrgBouncycastleAsn1ASN1EncodableVector_withInt_withBoolean_withOrgBouncycastleAsn1ASN1Encodable_(OrgBouncycastleAsn1CrmfCertTemplateBuilder *self, OrgBouncycastleAsn1ASN1EncodableVector *v, jint tagNo, jboolean isExplicit, id<OrgBouncycastleAsn1ASN1Encodable> obj) {
  if (obj != nil) {
    [((OrgBouncycastleAsn1ASN1EncodableVector *) nil_chk(v)) addWithOrgBouncycastleAsn1ASN1Encodable:[[OrgBouncycastleAsn1DERTaggedObject alloc] initWithBoolean:isExplicit withInt:tagNo withOrgBouncycastleAsn1ASN1Encodable:obj]];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1CrmfCertTemplateBuilder)
