//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/storage/MemoryPreferences.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/model/storage/MemoryPreferences.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/util/HashMap.h"

@interface ImActorModelStorageMemoryPreferences () {
 @public
  JavaUtilHashMap *items_;
}
@end

J2OBJC_FIELD_SETTER(ImActorModelStorageMemoryPreferences, items_, JavaUtilHashMap *)

@implementation ImActorModelStorageMemoryPreferences

- (void)putLongWithNSString:(NSString *)key
                   withLong:(jlong)v {
  @synchronized(self) {
    [((JavaUtilHashMap *) nil_chk(items_)) putWithId:key withId:JavaLangLong_valueOfWithLong_(v)];
  }
}

- (jlong)getLongWithNSString:(NSString *)key
                    withLong:(jlong)def {
  @synchronized(self) {
    if ([((JavaUtilHashMap *) nil_chk(items_)) containsKeyWithId:key]) {
      return [((JavaLangLong *) nil_chk((JavaLangLong *) check_class_cast([items_ getWithId:key], [JavaLangLong class]))) longLongValue];
    }
    return def;
  }
}

- (void)putIntWithNSString:(NSString *)key
                   withInt:(jint)v {
  [((JavaUtilHashMap *) nil_chk(items_)) putWithId:key withId:JavaLangInteger_valueOfWithInt_(v)];
}

- (jint)getIntWithNSString:(NSString *)key
                   withInt:(jint)def {
  if ([((JavaUtilHashMap *) nil_chk(items_)) containsKeyWithId:key]) {
    return [((JavaLangInteger *) nil_chk((JavaLangInteger *) check_class_cast([items_ getWithId:key], [JavaLangInteger class]))) intValue];
  }
  return def;
}

- (void)putBoolWithNSString:(NSString *)key
                withBoolean:(jboolean)v {
  [((JavaUtilHashMap *) nil_chk(items_)) putWithId:key withId:JavaLangBoolean_valueOfWithBoolean_(v)];
}

- (jboolean)getBoolWithNSString:(NSString *)key
                    withBoolean:(jboolean)def {
  if ([((JavaUtilHashMap *) nil_chk(items_)) containsKeyWithId:key]) {
    return [((JavaLangBoolean *) nil_chk((JavaLangBoolean *) check_class_cast([items_ getWithId:key], [JavaLangBoolean class]))) booleanValue];
  }
  return def;
}

- (void)putBytesWithNSString:(NSString *)key
               withByteArray:(IOSByteArray *)v {
  [((JavaUtilHashMap *) nil_chk(items_)) putWithId:key withId:v];
}

- (IOSByteArray *)getBytesWithNSString:(NSString *)key {
  if ([((JavaUtilHashMap *) nil_chk(items_)) containsKeyWithId:key]) {
    return (IOSByteArray *) check_class_cast([items_ getWithId:key], [IOSByteArray class]);
  }
  return nil;
}

- (void)putStringWithNSString:(NSString *)key
                 withNSString:(NSString *)v {
  [((JavaUtilHashMap *) nil_chk(items_)) putWithId:key withId:v];
}

- (NSString *)getStringWithNSString:(NSString *)key {
  if ([((JavaUtilHashMap *) nil_chk(items_)) containsKeyWithId:key]) {
    return (NSString *) check_class_cast([items_ getWithId:key], [NSString class]);
  }
  return nil;
}

- (instancetype)init {
  if (self = [super init]) {
    ImActorModelStorageMemoryPreferences_setAndConsume_items_(self, [[JavaUtilHashMap alloc] init]);
  }
  return self;
}

- (void)dealloc {
  RELEASE_(items_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ImActorModelStorageMemoryPreferences *)other {
  [super copyAllFieldsTo:other];
  ImActorModelStorageMemoryPreferences_set_items_(other, items_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "putLongWithNSString:withLong:", "putLong", "V", 0x21, NULL },
    { "getLongWithNSString:withLong:", "getLong", "J", 0x21, NULL },
    { "putIntWithNSString:withInt:", "putInt", "V", 0x1, NULL },
    { "getIntWithNSString:withInt:", "getInt", "I", 0x1, NULL },
    { "putBoolWithNSString:withBoolean:", "putBool", "V", 0x1, NULL },
    { "getBoolWithNSString:withBoolean:", "getBool", "Z", 0x1, NULL },
    { "putBytesWithNSString:withByteArray:", "putBytes", "V", 0x1, NULL },
    { "getBytesWithNSString:", "getBytes", "[B", 0x1, NULL },
    { "putStringWithNSString:withNSString:", "putString", "V", 0x1, NULL },
    { "getStringWithNSString:", "getString", "Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "items_", NULL, 0x2, "Ljava.util.HashMap;", NULL,  },
  };
  static const J2ObjcClassInfo _ImActorModelStorageMemoryPreferences = { 1, "MemoryPreferences", "im.actor.model.storage", NULL, 0x1, 11, methods, 1, fields, 0, NULL};
  return &_ImActorModelStorageMemoryPreferences;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ImActorModelStorageMemoryPreferences)
