//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/network/RpcCallback.java
//

#ifndef _AMRpcCallback_H_
#define _AMRpcCallback_H_

@class AMRpcException;
@class ImActorModelNetworkParserResponse;

#include "J2ObjC_header.h"

@protocol AMRpcCallback < NSObject, JavaObject >

- (void)onResultWithImActorModelNetworkParserResponse:(ImActorModelNetworkParserResponse *)response;

- (void)onErrorWithAMRpcException:(AMRpcException *)e;

@end

J2OBJC_EMPTY_STATIC_INIT(AMRpcCallback)

#define ImActorModelNetworkRpcCallback AMRpcCallback

J2OBJC_TYPE_LITERAL_HEADER(AMRpcCallback)

#endif // _AMRpcCallback_H_
