//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/crypto/params/DESedeParameters.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "org/bouncycastle/crypto/params/DESParameters.h"
#include "org/bouncycastle/crypto/params/DESedeParameters.h"

@implementation OrgBouncycastleCryptoParamsDESedeParameters

- (instancetype)initWithByteArray:(IOSByteArray *)key {
  if (self = [super initWithByteArray:key]) {
    if (OrgBouncycastleCryptoParamsDESedeParameters_isWeakKeyWithByteArray_withInt_withInt_(key, 0, ((IOSByteArray *) nil_chk(key))->size_)) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"attempt to create weak DESede key"];
    }
  }
  return self;
}

+ (jboolean)isWeakKeyWithByteArray:(IOSByteArray *)key
                           withInt:(jint)offset
                           withInt:(jint)length {
  return OrgBouncycastleCryptoParamsDESedeParameters_isWeakKeyWithByteArray_withInt_withInt_(key, offset, length);
}

+ (jboolean)isWeakKeyWithByteArray:(IOSByteArray *)key
                           withInt:(jint)offset {
  return OrgBouncycastleCryptoParamsDESedeParameters_isWeakKeyWithByteArray_withInt_(key, offset);
}

@end

jboolean OrgBouncycastleCryptoParamsDESedeParameters_isWeakKeyWithByteArray_withInt_withInt_(IOSByteArray *key, jint offset, jint length) {
  OrgBouncycastleCryptoParamsDESedeParameters_init();
  for (jint i = offset; i < length; i += OrgBouncycastleCryptoParamsDESParameters_DES_KEY_LENGTH) {
    if (OrgBouncycastleCryptoParamsDESParameters_isWeakKeyWithByteArray_withInt_(key, i)) {
      return YES;
    }
  }
  return NO;
}

jboolean OrgBouncycastleCryptoParamsDESedeParameters_isWeakKeyWithByteArray_withInt_(IOSByteArray *key, jint offset) {
  OrgBouncycastleCryptoParamsDESedeParameters_init();
  return OrgBouncycastleCryptoParamsDESedeParameters_isWeakKeyWithByteArray_withInt_withInt_(key, offset, ((IOSByteArray *) nil_chk(key))->size_ - offset);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleCryptoParamsDESedeParameters)
