//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/crypto/params/IESWithCipherParameters.java
//

#ifndef _OrgBouncycastleCryptoParamsIESWithCipherParameters_H_
#define _OrgBouncycastleCryptoParamsIESWithCipherParameters_H_

@class IOSByteArray;

#include "J2ObjC_header.h"
#include "org/bouncycastle/crypto/params/IESParameters.h"

@interface OrgBouncycastleCryptoParamsIESWithCipherParameters : OrgBouncycastleCryptoParamsIESParameters {
}

- (instancetype)initWithByteArray:(IOSByteArray *)derivation
                    withByteArray:(IOSByteArray *)encoding
                          withInt:(jint)macKeySize
                          withInt:(jint)cipherKeySize;

- (jint)getCipherKeySize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleCryptoParamsIESWithCipherParameters)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleCryptoParamsIESWithCipherParameters)

#endif // _OrgBouncycastleCryptoParamsIESWithCipherParameters_H_
