//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/crypto/params/NaccacheSternKeyParameters.java
//

#ifndef _OrgBouncycastleCryptoParamsNaccacheSternKeyParameters_H_
#define _OrgBouncycastleCryptoParamsNaccacheSternKeyParameters_H_

@class JavaMathBigInteger;

#include "J2ObjC_header.h"
#include "org/bouncycastle/crypto/params/AsymmetricKeyParameter.h"

@interface OrgBouncycastleCryptoParamsNaccacheSternKeyParameters : OrgBouncycastleCryptoParamsAsymmetricKeyParameter {
 @public
  jint lowerSigmaBound_;
}

- (instancetype)initWithBoolean:(jboolean)privateKey
         withJavaMathBigInteger:(JavaMathBigInteger *)g
         withJavaMathBigInteger:(JavaMathBigInteger *)n
                        withInt:(jint)lowerSigmaBound;

- (JavaMathBigInteger *)getG;

- (jint)getLowerSigmaBound;

- (JavaMathBigInteger *)getModulus;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleCryptoParamsNaccacheSternKeyParameters)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleCryptoParamsNaccacheSternKeyParameters)

#endif // _OrgBouncycastleCryptoParamsNaccacheSternKeyParameters_H_
