//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core-crypto/src/main/java/org/bouncycastle/math/ec/endo/GLVEndomorphism.java
//

#ifndef _OrgBouncycastleMathEcEndoGLVEndomorphism_H_
#define _OrgBouncycastleMathEcEndoGLVEndomorphism_H_

#include "J2ObjC_header.h"
#include "org/bouncycastle/math/ec/endo/ECEndomorphism.h"

@class IOSObjectArray;
@class JavaMathBigInteger;

@protocol OrgBouncycastleMathEcEndoGLVEndomorphism < OrgBouncycastleMathEcEndoECEndomorphism, NSObject, JavaObject >

- (IOSObjectArray *)decomposeScalarWithJavaMathBigInteger:(JavaMathBigInteger *)k;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleMathEcEndoGLVEndomorphism)

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleMathEcEndoGLVEndomorphism)

#endif // _OrgBouncycastleMathEcEndoGLVEndomorphism_H_
