//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core-crypto/src/main/java/org/bouncycastle/math/ec/endo/GLVTypeBParameters.java
//

#ifndef _OrgBouncycastleMathEcEndoGLVTypeBParameters_H_
#define _OrgBouncycastleMathEcEndoGLVTypeBParameters_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaMathBigInteger;

@interface OrgBouncycastleMathEcEndoGLVTypeBParameters : NSObject {
 @public
  JavaMathBigInteger *beta_;
  JavaMathBigInteger *lambda_;
  IOSObjectArray *v1_, *v2_;
  JavaMathBigInteger *g1_, *g2_;
  jint bits_;
}

#pragma mark Public

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)beta
                    withJavaMathBigInteger:(JavaMathBigInteger *)lambda
               withJavaMathBigIntegerArray:(IOSObjectArray *)v1
               withJavaMathBigIntegerArray:(IOSObjectArray *)v2
                    withJavaMathBigInteger:(JavaMathBigInteger *)g1
                    withJavaMathBigInteger:(JavaMathBigInteger *)g2
                                   withInt:(jint)bits;

- (JavaMathBigInteger *)getBeta;

- (jint)getBits;

- (JavaMathBigInteger *)getG1;

- (JavaMathBigInteger *)getG2;

- (JavaMathBigInteger *)getLambda;

- (IOSObjectArray *)getV1;

- (IOSObjectArray *)getV2;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleMathEcEndoGLVTypeBParameters)

J2OBJC_FIELD_SETTER(OrgBouncycastleMathEcEndoGLVTypeBParameters, beta_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleMathEcEndoGLVTypeBParameters, lambda_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleMathEcEndoGLVTypeBParameters, v1_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgBouncycastleMathEcEndoGLVTypeBParameters, v2_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgBouncycastleMathEcEndoGLVTypeBParameters, g1_, JavaMathBigInteger *)
J2OBJC_FIELD_SETTER(OrgBouncycastleMathEcEndoGLVTypeBParameters, g2_, JavaMathBigInteger *)

FOUNDATION_EXPORT void OrgBouncycastleMathEcEndoGLVTypeBParameters_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigIntegerArray_withJavaMathBigIntegerArray_withJavaMathBigInteger_withJavaMathBigInteger_withInt_(OrgBouncycastleMathEcEndoGLVTypeBParameters *self, JavaMathBigInteger *beta, JavaMathBigInteger *lambda, IOSObjectArray *v1, IOSObjectArray *v2, JavaMathBigInteger *g1, JavaMathBigInteger *g2, jint bits);

FOUNDATION_EXPORT OrgBouncycastleMathEcEndoGLVTypeBParameters *new_OrgBouncycastleMathEcEndoGLVTypeBParameters_initWithJavaMathBigInteger_withJavaMathBigInteger_withJavaMathBigIntegerArray_withJavaMathBigIntegerArray_withJavaMathBigInteger_withJavaMathBigInteger_withInt_(JavaMathBigInteger *beta, JavaMathBigInteger *lambda, IOSObjectArray *v1, IOSObjectArray *v2, JavaMathBigInteger *g1, JavaMathBigInteger *g2, jint bits) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleMathEcEndoGLVTypeBParameters)

#endif // _OrgBouncycastleMathEcEndoGLVTypeBParameters_H_
