platform :ios, '8.0'
use_frameworks!

workspace 'ActorSDK'
xcodeproj 'ActorSDK.xcodeproj'
xcodeproj 'ActorApp.xcodeproj'

inhibit_all_warnings!

# link_with 'ActorApp'

target 'ActorApp' do
    xcodeproj 'ActorApp.xcodeproj'

    # Core Tools
    pod 'RegexKitLite'
    pod 'CocoaAsyncSocket'
    pod 'zipzap'
    pod 'SwiftyJSON'

    # Main UI
    pod 'TTTAttributedLabel'
    pod 'RSKImageCropper'
    pod 'JDStatusBarNotification'
    pod 'YYImage', '0.9.3'
    pod 'YYCategories'
    pod 'DZNWebViewController'

    # Small UI
    pod 'VBFPopFlatButton'
    pod 'SZTextView'
        
    # Progress
    pod 'M13ProgressSuite'
    pod 'MBProgressHUD'
    
    # Calls
    # pod 'libjingle_peerconnection'
end

target 'ActorSDK' do
    xcodeproj 'ActorSDK.xcodeproj'

    # J2Objc Runtime
    pod 'J2ObjC-Framework'

    # Core Tools
    pod 'RegexKitLite'
    pod 'CocoaAsyncSocket'
    pod 'zipzap'
    pod 'SwiftyJSON'

    # Main UI
    pod 'TTTAttributedLabel'
    pod 'RSKImageCropper'
    pod 'JDStatusBarNotification'
    pod 'YYImage', '0.9.3'
    pod 'YYCategories'
    pod 'DZNWebViewController'

    # Small UI
    pod 'VBFPopFlatButton'
    pod 'SZTextView'
        
    # Progress
    pod 'M13ProgressSuite'
    pod 'MBProgressHUD'
    
    # Calls
    pod 'libjingle_peerconnection'
end
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end