//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/x9/X962Parameters.java
//

#ifndef _OrgBouncycastleAsn1X9X962Parameters_H_
#define _OrgBouncycastleAsn1X9X962Parameters_H_

@class OrgBouncycastleAsn1ASN1ObjectIdentifier;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1TaggedObject;
@class OrgBouncycastleAsn1X9X9ECParameters;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Choice.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

@interface OrgBouncycastleAsn1X9X962Parameters : OrgBouncycastleAsn1ASN1Object < OrgBouncycastleAsn1ASN1Choice > {
}

+ (OrgBouncycastleAsn1X9X962Parameters *)getInstanceWithId:(id)obj;

+ (OrgBouncycastleAsn1X9X962Parameters *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                                withBoolean:(jboolean)explicit_;

- (instancetype)initWithOrgBouncycastleAsn1X9X9ECParameters:(OrgBouncycastleAsn1X9X9ECParameters *)ecParameters;

- (instancetype)initWithOrgBouncycastleAsn1ASN1ObjectIdentifier:(OrgBouncycastleAsn1ASN1ObjectIdentifier *)namedCurve;

- (instancetype)initWithOrgBouncycastleAsn1ASN1Primitive:(OrgBouncycastleAsn1ASN1Primitive *)obj;

- (jboolean)isNamedCurve;

- (jboolean)isImplicitlyCA;

- (OrgBouncycastleAsn1ASN1Primitive *)getParameters;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1X9X962Parameters)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1X9X962Parameters *OrgBouncycastleAsn1X9X962Parameters_getInstanceWithId_(id obj);

FOUNDATION_EXPORT OrgBouncycastleAsn1X9X962Parameters *OrgBouncycastleAsn1X9X962Parameters_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1X9X962Parameters)

#endif // _OrgBouncycastleAsn1X9X962Parameters_H_
