platform :ios, '8.0'
use_frameworks!

workspace 'ActorApp'
xcodeproj 'ActorApp.xcodeproj'
xcodeproj '../actor-sdk/sdk-ios/ActorSDK.xcodeproj'
xcodeproj '../actor-sdk/sdk-ios/ActorCore.xcodeproj'

inhibit_all_warnings!

target 'ActorSDK' do
    xcodeproj '../actor-sdk/sdk-ios/ActorSDK.xcodeproj'
    
    pod 'RegexKitLite'
    pod 'CocoaAsyncSocket'
    pod 'zipzap'
    
    pod 'RMPhoneFormat', :git => 'https://github.com/actorapp/RMPhoneFormat'    
    
    pod 'J2ObjC-Framework'
end

target 'ActorCore' do
    xcodeproj '../actor-sdk/sdk-ios/ActorCore.xcodeproj'
    
    pod 'J2ObjC-Framework'
end

target 'ActorApp' do
	xcodeproj 'ActorApp.xcodeproj'

    # UI
    pod 'VBFPopFlatButton'
    pod 'MBProgressHUD'
    pod 'PSTAlertController'
    pod 'DZNPhotoPickerController'
    pod 'RMPhoneFormat', :git => 'https://github.com/actorapp/RMPhoneFormat'
    pod 'JVFloatLabeledTextField'
    pod 'CLTokenInputView'
    pod 'SZTextView'
    pod 'SlackTextViewController'

    pod 'NYTPhotoViewer'
    pod 'PEPhotoCropEditor'
    # pod 'TWMessageBarManager'
    pod 'LTNavigationBar'
    pod 'BlockAlertsAnd-ActionSheets'
    pod 'RMUniversalAlert'
    pod 'PSTAlertController'
    pod 'TTTAttributedLabel'
    pod 'M13ProgressSuite'
    # pod 'MDRadialProgress'

    # Tracking
    pod 'HockeySDK', '~> 3.8-RC'
    pod 'Fabric'
    pod 'Crashlytics'
end
