platform :ios, '7.0'
workspace 'ActorApp'
xcodeproj 'ActorApp.xcodeproj'

target 'ActorApp' do
	xcodeproj 'ActorApp.xcodeproj'

    # Core
    pod 'FMDB', :git => 'https://github.com/ccgus/fmdb'
    pod 'RegexKitLite', :inhibit_warnings => true
    pod 'CocoaAsyncSocket'

    # UI
    pod 'pop'
    pod 'VBFPopFlatButton'
    pod 'MBProgressHUD'
    pod 'PSTAlertController'
    pod 'DZNPhotoPickerController'
    pod 'RMPhoneFormat', :git => 'https://github.com/actorapp/RMPhoneFormat'
    pod 'JVFloatLabeledTextField'
    pod 'CLTokenInputView'

    pod 'SlackTextViewController', :git => 'https://github.com/actorapp/SlackTextViewController'

    pod 'NYTPhotoViewer'
    pod 'PEPhotoCropEditor'
    # pod 'TWMessageBarManager'
    pod 'LTNavigationBar'
    pod 'BlockAlertsAnd-ActionSheets'
    pod 'RMUniversalAlert'
    pod 'PSTAlertController'
    pod 'TTTAttributedLabel'
    pod 'M13ProgressSuite'
    # pod 'MDRadialProgress'

    # Tracking
    pod 'HockeySDK', '~> 3.8-RC'
    # pod 'SplunkMint'
end
