//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/math/ec/custom/sec/SecP224R1FieldElement.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/math/BigInteger.h"
#include "org/bouncycastle/math/ec/ECFieldElement.h"
#include "org/bouncycastle/math/ec/custom/sec/SecP224R1Curve.h"
#include "org/bouncycastle/math/ec/custom/sec/SecP224R1Field.h"
#include "org/bouncycastle/math/ec/custom/sec/SecP224R1FieldElement.h"
#include "org/bouncycastle/math/raw/Mod.h"
#include "org/bouncycastle/math/raw/Nat.h"
#include "org/bouncycastle/math/raw/Nat224.h"
#include "org/bouncycastle/util/Arrays.h"

__attribute__((unused)) static jboolean OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_isSquareWithIntArray_(IOSIntArray *x);
__attribute__((unused)) static void OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RMWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(IOSIntArray *nc, IOSIntArray *d0, IOSIntArray *e0, IOSIntArray *d1, IOSIntArray *e1, IOSIntArray *f1, IOSIntArray *t);
__attribute__((unused)) static void OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RPWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(IOSIntArray *nc, IOSIntArray *d1, IOSIntArray *e1, IOSIntArray *f1, IOSIntArray *t);
__attribute__((unused)) static void OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RSWithIntArray_withIntArray_withIntArray_withIntArray_(IOSIntArray *d, IOSIntArray *e, IOSIntArray *f, IOSIntArray *t);
__attribute__((unused)) static jboolean OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_trySqrtWithIntArray_withIntArray_withIntArray_(IOSIntArray *nc, IOSIntArray *r, IOSIntArray *t);

@interface OrgBouncycastleMathEcCustomSecSecP224R1FieldElement ()

+ (jboolean)isSquareWithIntArray:(IOSIntArray *)x;

+ (void)RMWithIntArray:(IOSIntArray *)nc
          withIntArray:(IOSIntArray *)d0
          withIntArray:(IOSIntArray *)e0
          withIntArray:(IOSIntArray *)d1
          withIntArray:(IOSIntArray *)e1
          withIntArray:(IOSIntArray *)f1
          withIntArray:(IOSIntArray *)t;

+ (void)RPWithIntArray:(IOSIntArray *)nc
          withIntArray:(IOSIntArray *)d1
          withIntArray:(IOSIntArray *)e1
          withIntArray:(IOSIntArray *)f1
          withIntArray:(IOSIntArray *)t;

+ (void)RSWithIntArray:(IOSIntArray *)d
          withIntArray:(IOSIntArray *)e
          withIntArray:(IOSIntArray *)f
          withIntArray:(IOSIntArray *)t;

+ (jboolean)trySqrtWithIntArray:(IOSIntArray *)nc
                   withIntArray:(IOSIntArray *)r
                   withIntArray:(IOSIntArray *)t;
@end

BOOL OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_initialized = NO;

@implementation OrgBouncycastleMathEcCustomSecSecP224R1FieldElement

JavaMathBigInteger * OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_Q_;

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  if (self = [super init]) {
    if (x == nil || [x signum] < 0 || [x compareToWithId:OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_Q_] >= 0) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"x value invalid for SecP224R1FieldElement"];
    }
    self->x_ = OrgBouncycastleMathEcCustomSecSecP224R1Field_fromBigIntegerWithJavaMathBigInteger_(x);
  }
  return self;
}

- (instancetype)init {
  if (self = [super init]) {
    self->x_ = OrgBouncycastleMathRawNat224_create();
  }
  return self;
}

- (instancetype)initWithIntArray:(IOSIntArray *)x {
  if (self = [super init]) {
    self->x_ = x;
  }
  return self;
}

- (jboolean)isZero {
  return OrgBouncycastleMathRawNat224_isZeroWithIntArray_(x_);
}

- (jboolean)isOne {
  return OrgBouncycastleMathRawNat224_isOneWithIntArray_(x_);
}

- (jboolean)testBitZero {
  return OrgBouncycastleMathRawNat224_getBitWithIntArray_withInt_(x_, 0) == 1;
}

- (JavaMathBigInteger *)toBigInteger {
  return OrgBouncycastleMathRawNat224_toBigIntegerWithIntArray_(x_);
}

- (NSString *)getFieldName {
  return @"SecP224R1Field";
}

- (jint)getFieldSize {
  return [((JavaMathBigInteger *) nil_chk(OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_Q_)) bitLength];
}

- (OrgBouncycastleMathEcECFieldElement *)addWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_addWithIntArray_withIntArray_withIntArray_(x_, ((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) check_class_cast(b, [OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]))))->x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)addOne {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_addOneWithIntArray_withIntArray_(x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)subtractWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_subtractWithIntArray_withIntArray_withIntArray_(x_, ((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) check_class_cast(b, [OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]))))->x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)multiplyWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(x_, ((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) check_class_cast(b, [OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]))))->x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)divideWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)b {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathRawMod_invertWithIntArray_withIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP224R1Field_get_P_(), ((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) check_class_cast(b, [OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]))))->x_, z);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(z, x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)negate {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_negateWithIntArray_withIntArray_(x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)square {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_squareWithIntArray_withIntArray_(x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)invert {
  IOSIntArray *z = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathRawMod_invertWithIntArray_withIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP224R1Field_get_P_(), x_, z);
  return [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:z];
}

- (OrgBouncycastleMathEcECFieldElement *)sqrt {
  IOSIntArray *c = self->x_;
  if (OrgBouncycastleMathRawNat224_isZeroWithIntArray_(c) || OrgBouncycastleMathRawNat224_isOneWithIntArray_(c)) {
    return self;
  }
  IOSIntArray *nc = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_negateWithIntArray_withIntArray_(c, nc);
  IOSIntArray *r = OrgBouncycastleMathRawMod_randomWithIntArray_(OrgBouncycastleMathEcCustomSecSecP224R1Field_get_P_());
  IOSIntArray *t = OrgBouncycastleMathRawNat224_create();
  if (!OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_isSquareWithIntArray_(c)) {
    return nil;
  }
  while (!OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_trySqrtWithIntArray_withIntArray_withIntArray_(nc, r, t)) {
    OrgBouncycastleMathEcCustomSecSecP224R1Field_addOneWithIntArray_withIntArray_(r, r);
  }
  OrgBouncycastleMathEcCustomSecSecP224R1Field_squareWithIntArray_withIntArray_(t, r);
  return OrgBouncycastleMathRawNat224_eqWithIntArray_withIntArray_(c, r) ? [[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement alloc] initWithIntArray:t] : nil;
}

- (jboolean)isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (!([other isKindOfClass:[OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]])) {
    return NO;
  }
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *o = (OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) check_class_cast(other, [OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]);
  return OrgBouncycastleMathRawNat224_eqWithIntArray_withIntArray_(x_, ((OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *) nil_chk(o))->x_);
}

- (NSUInteger)hash {
  return ((jint) [((JavaMathBigInteger *) nil_chk(OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_Q_)) hash]) ^ OrgBouncycastleUtilArrays_hashCodeWithIntArray_withInt_withInt_(x_, 0, 7);
}

+ (jboolean)isSquareWithIntArray:(IOSIntArray *)x {
  return OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_isSquareWithIntArray_(x);
}

+ (void)RMWithIntArray:(IOSIntArray *)nc
          withIntArray:(IOSIntArray *)d0
          withIntArray:(IOSIntArray *)e0
          withIntArray:(IOSIntArray *)d1
          withIntArray:(IOSIntArray *)e1
          withIntArray:(IOSIntArray *)f1
          withIntArray:(IOSIntArray *)t {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RMWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(nc, d0, e0, d1, e1, f1, t);
}

+ (void)RPWithIntArray:(IOSIntArray *)nc
          withIntArray:(IOSIntArray *)d1
          withIntArray:(IOSIntArray *)e1
          withIntArray:(IOSIntArray *)f1
          withIntArray:(IOSIntArray *)t {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RPWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(nc, d1, e1, f1, t);
}

+ (void)RSWithIntArray:(IOSIntArray *)d
          withIntArray:(IOSIntArray *)e
          withIntArray:(IOSIntArray *)f
          withIntArray:(IOSIntArray *)t {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RSWithIntArray_withIntArray_withIntArray_withIntArray_(d, e, f, t);
}

+ (jboolean)trySqrtWithIntArray:(IOSIntArray *)nc
                   withIntArray:(IOSIntArray *)r
                   withIntArray:(IOSIntArray *)t {
  return OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_trySqrtWithIntArray_withIntArray_withIntArray_(nc, r, t);
}

- (void)copyAllFieldsTo:(OrgBouncycastleMathEcCustomSecSecP224R1FieldElement *)other {
  [super copyAllFieldsTo:other];
  other->x_ = x_;
}

+ (void)initialize {
  if (self == [OrgBouncycastleMathEcCustomSecSecP224R1FieldElement class]) {
    OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_Q_ = OrgBouncycastleMathEcCustomSecSecP224R1Curve_get_q_();
    J2OBJC_SET_INITIALIZED(OrgBouncycastleMathEcCustomSecSecP224R1FieldElement)
  }
}

@end

jboolean OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_isSquareWithIntArray_(IOSIntArray *x) {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_init();
  IOSIntArray *t1 = OrgBouncycastleMathRawNat224_create();
  IOSIntArray *t2 = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(x, t1);
  for (jint i = 0; i < 7; ++i) {
    OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(t1, t2);
    OrgBouncycastleMathEcCustomSecSecP224R1Field_squareNWithIntArray_withInt_withIntArray_(t1, LShift32(1, i), t1);
    OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(t1, t2, t1);
  }
  OrgBouncycastleMathEcCustomSecSecP224R1Field_squareNWithIntArray_withInt_withIntArray_(t1, 95, t1);
  return OrgBouncycastleMathRawNat224_isOneWithIntArray_(t1);
}

void OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RMWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(IOSIntArray *nc, IOSIntArray *d0, IOSIntArray *e0, IOSIntArray *d1, IOSIntArray *e1, IOSIntArray *f1, IOSIntArray *t) {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_init();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(e1, e0, t);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(t, nc, t);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(d1, d0, f1);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_addWithIntArray_withIntArray_withIntArray_(f1, t, f1);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(d1, e0, t);
  OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(f1, d1);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(e1, d0, e1);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_addWithIntArray_withIntArray_withIntArray_(e1, t, e1);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_squareWithIntArray_withIntArray_(e1, f1);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(f1, nc, f1);
}

void OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RPWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(IOSIntArray *nc, IOSIntArray *d1, IOSIntArray *e1, IOSIntArray *f1, IOSIntArray *t) {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_init();
  OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(nc, f1);
  IOSIntArray *d0 = OrgBouncycastleMathRawNat224_create();
  IOSIntArray *e0 = OrgBouncycastleMathRawNat224_create();
  for (jint i = 0; i < 7; ++i) {
    OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(d1, d0);
    OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(e1, e0);
    jint j = LShift32(1, i);
    while (--j >= 0) {
      OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RSWithIntArray_withIntArray_withIntArray_withIntArray_(d1, e1, f1, t);
    }
    OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RMWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(nc, d0, e0, d1, e1, f1, t);
  }
}

void OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RSWithIntArray_withIntArray_withIntArray_withIntArray_(IOSIntArray *d, IOSIntArray *e, IOSIntArray *f, IOSIntArray *t) {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_init();
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(e, d, e);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_twiceWithIntArray_withIntArray_(e, e);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_squareWithIntArray_withIntArray_(d, t);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_addWithIntArray_withIntArray_withIntArray_(f, t, d);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(f, t, f);
  jint c = OrgBouncycastleMathRawNat_shiftUpBitsWithInt_withIntArray_withInt_withInt_(7, f, 2, 0);
  OrgBouncycastleMathEcCustomSecSecP224R1Field_reduce32WithInt_withIntArray_(c, f);
}

jboolean OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_trySqrtWithIntArray_withIntArray_withIntArray_(IOSIntArray *nc, IOSIntArray *r, IOSIntArray *t) {
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_init();
  IOSIntArray *d1 = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(r, d1);
  IOSIntArray *e1 = OrgBouncycastleMathRawNat224_create();
  *IOSIntArray_GetRef(nil_chk(e1), 0) = 1;
  IOSIntArray *f1 = OrgBouncycastleMathRawNat224_create();
  OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RPWithIntArray_withIntArray_withIntArray_withIntArray_withIntArray_(nc, d1, e1, f1, t);
  IOSIntArray *d0 = OrgBouncycastleMathRawNat224_create();
  IOSIntArray *e0 = OrgBouncycastleMathRawNat224_create();
  for (jint k = 1; k < 96; ++k) {
    OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(d1, d0);
    OrgBouncycastleMathRawNat224_copy__WithIntArray_withIntArray_(e1, e0);
    OrgBouncycastleMathEcCustomSecSecP224R1FieldElement_RSWithIntArray_withIntArray_withIntArray_withIntArray_(d1, e1, f1, t);
    if (OrgBouncycastleMathRawNat224_isZeroWithIntArray_(d1)) {
      OrgBouncycastleMathRawMod_invertWithIntArray_withIntArray_withIntArray_(OrgBouncycastleMathEcCustomSecSecP224R1Field_get_P_(), e0, t);
      OrgBouncycastleMathEcCustomSecSecP224R1Field_multiplyWithIntArray_withIntArray_withIntArray_(t, d0, t);
      return YES;
    }
  }
  return NO;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcCustomSecSecP224R1FieldElement)
