//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/droidkit/bser/BserUnknownFields.java
//

#ifndef _BSBserUnknownFields_H_
#define _BSBserUnknownFields_H_

@class IOSByteArray;
@class JavaUtilArrayList;

#include "J2ObjC_header.h"

@interface BSBserUnknownFields : NSObject {
}

- (void)addWithInt:(jint)id_
           withInt:(jint)type
     withByteArray:(IOSByteArray *)field;

- (void)addWithInt:(jint)id_
           withInt:(jint)type
          withLong:(jlong)value;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(BSBserUnknownFields)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef BSBserUnknownFields ImActorModelDroidkitBserBserUnknownFields;

J2OBJC_TYPE_LITERAL_HEADER(BSBserUnknownFields)

#endif // _BSBserUnknownFields_H_
