//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/entity/DialogBuilder.java
//

#ifndef _ImActorModelEntityDialogBuilder_H_
#define _ImActorModelEntityDialogBuilder_H_

@class ImActorModelEntityAvatar;
@class ImActorModelEntityDialog;
@class ImActorModelEntityDialog_ContentTypeEnum;
@class ImActorModelEntityMessageStateEnum;
@class ImActorModelEntityPeer;

#include "J2ObjC_header.h"

@interface ImActorModelEntityDialogBuilder : NSObject {
}

- (instancetype)init;

- (instancetype)initWithImActorModelEntityDialog:(ImActorModelEntityDialog *)dialog;

- (ImActorModelEntityDialogBuilder *)setPeerWithImActorModelEntityPeer:(ImActorModelEntityPeer *)peer;

- (ImActorModelEntityDialogBuilder *)setSortKeyWithLong:(jlong)sortKey;

- (ImActorModelEntityDialogBuilder *)setDialogTitleWithNSString:(NSString *)dialogTitle;

- (ImActorModelEntityDialogBuilder *)setUnreadCountWithInt:(jint)unreadCount;

- (ImActorModelEntityDialogBuilder *)setRidWithLong:(jlong)rid;

- (ImActorModelEntityDialogBuilder *)setMessageTypeWithImActorModelEntityDialog_ContentTypeEnum:(ImActorModelEntityDialog_ContentTypeEnum *)messageType;

- (ImActorModelEntityDialogBuilder *)setTextWithNSString:(NSString *)text;

- (ImActorModelEntityDialogBuilder *)setStatusWithImActorModelEntityMessageStateEnum:(ImActorModelEntityMessageStateEnum *)status;

- (ImActorModelEntityDialogBuilder *)setSenderIdWithInt:(jint)senderId;

- (ImActorModelEntityDialogBuilder *)setTimeWithLong:(jlong)time;

- (ImActorModelEntityDialogBuilder *)setRelatedUidWithInt:(jint)relatedUid;

- (ImActorModelEntityDialogBuilder *)setDialogAvatarWithImActorModelEntityAvatar:(ImActorModelEntityAvatar *)avatar;

- (ImActorModelEntityDialog *)createDialog;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorModelEntityDialogBuilder)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(ImActorModelEntityDialogBuilder)

#endif // _ImActorModelEntityDialogBuilder_H_
