//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/entity/FileLocation.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/entity/FileLocation.h"

@interface ImActorModelEntityFileLocation () {
 @public
  jlong fileId_;
  jlong accessHash_;
  jint fileSize_;
}
@end

@implementation ImActorModelEntityFileLocation

- (instancetype)initWithLong:(jlong)fileId
                    withLong:(jlong)accessHash
                     withInt:(jint)fileSize {
  if (self = [super init]) {
    self->fileId_ = fileId;
    self->accessHash_ = accessHash;
    self->fileSize_ = fileSize;
  }
  return self;
}

- (jint)getFileSize {
  return fileSize_;
}

- (jlong)getFileId {
  return fileId_;
}

- (jlong)getAccessHash {
  return accessHash_;
}

- (jboolean)isEqual:(id)o {
  if (self == o) return YES;
  if (o == nil || [self getClass] != [o getClass]) return NO;
  ImActorModelEntityFileLocation *that = (ImActorModelEntityFileLocation *) check_class_cast(o, [ImActorModelEntityFileLocation class]);
  if (fileId_ != ((ImActorModelEntityFileLocation *) nil_chk(that))->fileId_) return NO;
  return YES;
}

- (NSUInteger)hash {
  return (jint) (fileId_ ^ (URShift64(fileId_, 32)));
}

- (void)copyAllFieldsTo:(ImActorModelEntityFileLocation *)other {
  [super copyAllFieldsTo:other];
  other->fileId_ = fileId_;
  other->accessHash_ = accessHash_;
  other->fileSize_ = fileSize_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithLong:withLong:withInt:", "FileLocation", NULL, 0x1, NULL },
    { "getFileSize", NULL, "I", 0x1, NULL },
    { "getFileId", NULL, "J", 0x1, NULL },
    { "getAccessHash", NULL, "J", 0x1, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL },
    { "hash", "hashCode", "I", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "fileId_", NULL, 0x12, "J", NULL,  },
    { "accessHash_", NULL, 0x12, "J", NULL,  },
    { "fileSize_", NULL, 0x12, "I", NULL,  },
  };
  static const J2ObjcClassInfo _ImActorModelEntityFileLocation = { 1, "FileLocation", "im.actor.model.entity", NULL, 0x1, 6, methods, 3, fields, 0, NULL};
  return &_ImActorModelEntityFileLocation;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ImActorModelEntityFileLocation)
