//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/entity/MessageState.java
//

#ifndef _ImActorModelEntityMessageState_H_
#define _ImActorModelEntityMessageState_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

typedef NS_ENUM(NSUInteger, ImActorModelEntityMessageState) {
  ImActorModelEntityMessageState_PENDING = 0,
  ImActorModelEntityMessageState_SENT = 1,
  ImActorModelEntityMessageState_RECEIVED = 2,
  ImActorModelEntityMessageState_READ = 3,
  ImActorModelEntityMessageState_ERROR = 4,
  ImActorModelEntityMessageState_UNKNOWN = 5,
};

@interface ImActorModelEntityMessageStateEnum : JavaLangEnum < NSCopying > {
 @public
  jint value_;
}

- (instancetype)initWithInt:(jint)value
               withNSString:(NSString *)__name
                    withInt:(jint)__ordinal;

- (jint)getValue;

+ (ImActorModelEntityMessageStateEnum *)fromValueWithInt:(jint)value;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ImActorModelEntityMessageStateEnum_values();

+ (ImActorModelEntityMessageStateEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ImActorModelEntityMessageStateEnum *ImActorModelEntityMessageStateEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ImActorModelEntityMessageStateEnum_initialized;
J2OBJC_STATIC_INIT(ImActorModelEntityMessageStateEnum)

FOUNDATION_EXPORT ImActorModelEntityMessageStateEnum *ImActorModelEntityMessageStateEnum_fromValueWithInt_(jint value);

FOUNDATION_EXPORT ImActorModelEntityMessageStateEnum *ImActorModelEntityMessageStateEnum_values_[];

#define ImActorModelEntityMessageStateEnum_PENDING ImActorModelEntityMessageStateEnum_values_[ImActorModelEntityMessageState_PENDING]
J2OBJC_ENUM_CONSTANT_GETTER(ImActorModelEntityMessageStateEnum, PENDING)

#define ImActorModelEntityMessageStateEnum_SENT ImActorModelEntityMessageStateEnum_values_[ImActorModelEntityMessageState_SENT]
J2OBJC_ENUM_CONSTANT_GETTER(ImActorModelEntityMessageStateEnum, SENT)

#define ImActorModelEntityMessageStateEnum_RECEIVED ImActorModelEntityMessageStateEnum_values_[ImActorModelEntityMessageState_RECEIVED]
J2OBJC_ENUM_CONSTANT_GETTER(ImActorModelEntityMessageStateEnum, RECEIVED)

#define ImActorModelEntityMessageStateEnum_READ ImActorModelEntityMessageStateEnum_values_[ImActorModelEntityMessageState_READ]
J2OBJC_ENUM_CONSTANT_GETTER(ImActorModelEntityMessageStateEnum, READ)

#define ImActorModelEntityMessageStateEnum_ERROR ImActorModelEntityMessageStateEnum_values_[ImActorModelEntityMessageState_ERROR]
J2OBJC_ENUM_CONSTANT_GETTER(ImActorModelEntityMessageStateEnum, ERROR)

#define ImActorModelEntityMessageStateEnum_UNKNOWN ImActorModelEntityMessageStateEnum_values_[ImActorModelEntityMessageState_UNKNOWN]
J2OBJC_ENUM_CONSTANT_GETTER(ImActorModelEntityMessageStateEnum, UNKNOWN)

J2OBJC_TYPE_LITERAL_HEADER(ImActorModelEntityMessageStateEnum)

#endif // _ImActorModelEntityMessageState_H_
