//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/entity/PeerType.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/entity/PeerType.h"
#include "java/lang/IllegalArgumentException.h"

BOOL AMPeerTypeEnum_initialized = NO;

AMPeerTypeEnum *AMPeerTypeEnum_values_[3];

@implementation AMPeerTypeEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

IOSObjectArray *AMPeerTypeEnum_values() {
  AMPeerTypeEnum_init();
  return [IOSObjectArray arrayWithObjects:AMPeerTypeEnum_values_ count:3 type:AMPeerTypeEnum_class_()];
}
+ (IOSObjectArray *)values {
  return AMPeerTypeEnum_values();
}

+ (AMPeerTypeEnum *)valueOfWithNSString:(NSString *)name {
  return AMPeerTypeEnum_valueOfWithNSString_(name);
}

AMPeerTypeEnum *AMPeerTypeEnum_valueOfWithNSString_(NSString *name) {
  AMPeerTypeEnum_init();
  for (int i = 0; i < 3; i++) {
    AMPeerTypeEnum *e = AMPeerTypeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [AMPeerTypeEnum class]) {
    AMPeerTypeEnum_PRIVATE = [[AMPeerTypeEnum alloc] initWithNSString:@"PRIVATE" withInt:0];
    AMPeerTypeEnum_GROUP = [[AMPeerTypeEnum alloc] initWithNSString:@"GROUP" withInt:1];
    AMPeerTypeEnum_EMAIL = [[AMPeerTypeEnum alloc] initWithNSString:@"EMAIL" withInt:2];
    J2OBJC_SET_INITIALIZED(AMPeerTypeEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "init", NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "PRIVATE", "PRIVATE", 0x4019, "Lim.actor.model.entity.PeerType;", &AMPeerTypeEnum_PRIVATE,  },
    { "GROUP", "GROUP", 0x4019, "Lim.actor.model.entity.PeerType;", &AMPeerTypeEnum_GROUP,  },
    { "EMAIL", "EMAIL", 0x4019, "Lim.actor.model.entity.PeerType;", &AMPeerTypeEnum_EMAIL,  },
  };
  static const char *superclass_type_args[] = {"Lim.actor.model.entity.PeerType;"};
  static const J2ObjcClassInfo _AMPeerTypeEnum = { 1, "PeerType", "im.actor.model.entity", NULL, 0x4011, 1, methods, 3, fields, 1, superclass_type_args};
  return &_AMPeerTypeEnum;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AMPeerTypeEnum)
