package im.actor.core.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import java.io.IOException;

public enum ApiSearchPeerType {

    GROUPS(1),
    CONTACTS(2),
    PUBLIC(3),
    UNSUPPORTED_VALUE(-1);

    private int value;

    ApiSearchPeerType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static ApiSearchPeerType parse(int value) throws IOException {
        switch(value) {
            case 1: return ApiSearchPeerType.GROUPS;
            case 2: return ApiSearchPeerType.CONTACTS;
            case 3: return ApiSearchPeerType.PUBLIC;
            default: return ApiSearchPeerType.UNSUPPORTED_VALUE;
        }
    }
}
