package im.actor.model.api;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.model.droidkit.bser.Bser;
import im.actor.model.droidkit.bser.BserParser;
import im.actor.model.droidkit.bser.BserObject;
import im.actor.model.droidkit.bser.BserValues;
import im.actor.model.droidkit.bser.BserWriter;
import im.actor.model.droidkit.bser.DataInput;
import static im.actor.model.droidkit.bser.Utils.*;
import java.io.IOException;
import im.actor.model.network.parser.*;
import java.util.List;
import java.util.ArrayList;

public class UploadConfig extends BserObject {

    private byte[] serverData;

    public UploadConfig(byte[] serverData) {
        this.serverData = serverData;
    }

    public UploadConfig() {

    }

    public byte[] getServerData() {
        return this.serverData;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        this.serverData = values.getBytes(1);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        if (this.serverData == null) {
            throw new IOException();
        }
        writer.writeBytes(1, this.serverData);
    }

    @Override
    public String toString() {
        String res = "struct UploadConfig{";
        res += "serverData=" + byteArrayToStringCompact(this.serverData);
        res += "}";
        return res;
    }

}
