//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/cms/Attributes.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1EncodableVector.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Set.h"
#include "org/bouncycastle/asn1/DLSet.h"
#include "org/bouncycastle/asn1/cms/Attribute.h"
#include "org/bouncycastle/asn1/cms/Attributes.h"

@interface OrgBouncycastleAsn1CmsAttributes () {
 @public
  OrgBouncycastleAsn1ASN1Set *attributes_;
}
- (instancetype)initWithOrgBouncycastleAsn1ASN1Set:(OrgBouncycastleAsn1ASN1Set *)set;
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1CmsAttributes, attributes_, OrgBouncycastleAsn1ASN1Set *)

@implementation OrgBouncycastleAsn1CmsAttributes

- (instancetype)initWithOrgBouncycastleAsn1ASN1Set:(OrgBouncycastleAsn1ASN1Set *)set {
  if (self = [super init]) {
    attributes_ = set;
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1EncodableVector:(OrgBouncycastleAsn1ASN1EncodableVector *)v {
  if (self = [super init]) {
    attributes_ = [[OrgBouncycastleAsn1DLSet alloc] initWithOrgBouncycastleAsn1ASN1EncodableVector:v];
  }
  return self;
}

+ (OrgBouncycastleAsn1CmsAttributes *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1CmsAttributes_getInstanceWithId_(obj);
}

- (IOSObjectArray *)getAttributes {
  IOSObjectArray *rv = [IOSObjectArray newArrayWithLength:[((OrgBouncycastleAsn1ASN1Set *) nil_chk(attributes_)) size] type:OrgBouncycastleAsn1CmsAttribute_class_()];
  for (jint i = 0; i != rv->size_; i++) {
    IOSObjectArray_Set(rv, i, OrgBouncycastleAsn1CmsAttribute_getInstanceWithId_([attributes_ getObjectAtWithInt:i]));
  }
  return rv;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return attributes_;
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1CmsAttributes *)other {
  [super copyAllFieldsTo:other];
  other->attributes_ = attributes_;
}

@end

OrgBouncycastleAsn1CmsAttributes *OrgBouncycastleAsn1CmsAttributes_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1CmsAttributes_init();
  if ([obj isKindOfClass:[OrgBouncycastleAsn1CmsAttributes class]]) {
    return (OrgBouncycastleAsn1CmsAttributes *) check_class_cast(obj, [OrgBouncycastleAsn1CmsAttributes class]);
  }
  else if (obj != nil) {
    return [[OrgBouncycastleAsn1CmsAttributes alloc] initWithOrgBouncycastleAsn1ASN1Set:OrgBouncycastleAsn1ASN1Set_getInstanceWithId_(obj)];
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1CmsAttributes)
