//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/cms/TimeStampTokenEvidence.java
//

#ifndef _OrgBouncycastleAsn1CmsTimeStampTokenEvidence_H_
#define _OrgBouncycastleAsn1CmsTimeStampTokenEvidence_H_

@class IOSObjectArray;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Sequence;
@class OrgBouncycastleAsn1ASN1TaggedObject;
@class OrgBouncycastleAsn1CmsTimeStampAndCRL;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

@interface OrgBouncycastleAsn1CmsTimeStampTokenEvidence : OrgBouncycastleAsn1ASN1Object {
}

- (instancetype)initWithOrgBouncycastleAsn1CmsTimeStampAndCRLArray:(IOSObjectArray *)timeStampAndCRLs;

- (instancetype)initWithOrgBouncycastleAsn1CmsTimeStampAndCRL:(OrgBouncycastleAsn1CmsTimeStampAndCRL *)timeStampAndCRL;

+ (OrgBouncycastleAsn1CmsTimeStampTokenEvidence *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)tagged
                                                                                         withBoolean:(jboolean)explicit_;

+ (OrgBouncycastleAsn1CmsTimeStampTokenEvidence *)getInstanceWithId:(id)obj;

- (IOSObjectArray *)toTimeStampAndCRLArray;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1CmsTimeStampTokenEvidence)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1CmsTimeStampTokenEvidence *OrgBouncycastleAsn1CmsTimeStampTokenEvidence_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *tagged, jboolean explicit_);

FOUNDATION_EXPORT OrgBouncycastleAsn1CmsTimeStampTokenEvidence *OrgBouncycastleAsn1CmsTimeStampTokenEvidence_getInstanceWithId_(id obj);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1CmsTimeStampTokenEvidence)

#endif // _OrgBouncycastleAsn1CmsTimeStampTokenEvidence_H_
