//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/esf/CompleteRevocationRefs.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/util/Enumeration.h"
#include "org/bouncycastle/asn1/ASN1Encodable.h"
#include "org/bouncycastle/asn1/ASN1Primitive.h"
#include "org/bouncycastle/asn1/ASN1Sequence.h"
#include "org/bouncycastle/asn1/DERSequence.h"
#include "org/bouncycastle/asn1/esf/CompleteRevocationRefs.h"
#include "org/bouncycastle/asn1/esf/CrlOcspRef.h"

@interface OrgBouncycastleAsn1EsfCompleteRevocationRefs () {
 @public
  OrgBouncycastleAsn1ASN1Sequence *crlOcspRefs_;
}
- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq;
@end

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1EsfCompleteRevocationRefs, crlOcspRefs_, OrgBouncycastleAsn1ASN1Sequence *)

@implementation OrgBouncycastleAsn1EsfCompleteRevocationRefs

+ (OrgBouncycastleAsn1EsfCompleteRevocationRefs *)getInstanceWithId:(id)obj {
  return OrgBouncycastleAsn1EsfCompleteRevocationRefs_getInstanceWithId_(obj);
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1Sequence:(OrgBouncycastleAsn1ASN1Sequence *)seq {
  if (self = [super init]) {
    id<JavaUtilEnumeration> seqEnum = [((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(seq)) getObjects];
    while ([((id<JavaUtilEnumeration>) nil_chk(seqEnum)) hasMoreElements]) {
      OrgBouncycastleAsn1EsfCrlOcspRef_getInstanceWithId_([seqEnum nextElement]);
    }
    self->crlOcspRefs_ = seq;
  }
  return self;
}

- (instancetype)initWithOrgBouncycastleAsn1EsfCrlOcspRefArray:(IOSObjectArray *)crlOcspRefs {
  if (self = [super init]) {
    self->crlOcspRefs_ = [[OrgBouncycastleAsn1DERSequence alloc] initWithOrgBouncycastleAsn1ASN1EncodableArray:crlOcspRefs];
  }
  return self;
}

- (IOSObjectArray *)getCrlOcspRefs {
  IOSObjectArray *result = [IOSObjectArray newArrayWithLength:[((OrgBouncycastleAsn1ASN1Sequence *) nil_chk(self->crlOcspRefs_)) size] type:OrgBouncycastleAsn1EsfCrlOcspRef_class_()];
  for (jint idx = 0; idx < result->size_; idx++) {
    IOSObjectArray_Set(result, idx, OrgBouncycastleAsn1EsfCrlOcspRef_getInstanceWithId_([self->crlOcspRefs_ getObjectAtWithInt:idx]));
  }
  return result;
}

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive {
  return self->crlOcspRefs_;
}

- (void)copyAllFieldsTo:(OrgBouncycastleAsn1EsfCompleteRevocationRefs *)other {
  [super copyAllFieldsTo:other];
  other->crlOcspRefs_ = crlOcspRefs_;
}

@end

OrgBouncycastleAsn1EsfCompleteRevocationRefs *OrgBouncycastleAsn1EsfCompleteRevocationRefs_getInstanceWithId_(id obj) {
  OrgBouncycastleAsn1EsfCompleteRevocationRefs_init();
  if ([obj isKindOfClass:[OrgBouncycastleAsn1EsfCompleteRevocationRefs class]]) {
    return (OrgBouncycastleAsn1EsfCompleteRevocationRefs *) check_class_cast(obj, [OrgBouncycastleAsn1EsfCompleteRevocationRefs class]);
  }
  else if (obj != nil) {
    return [[OrgBouncycastleAsn1EsfCompleteRevocationRefs alloc] initWithOrgBouncycastleAsn1ASN1Sequence:OrgBouncycastleAsn1ASN1Sequence_getInstanceWithId_(obj)];
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleAsn1EsfCompleteRevocationRefs)
