//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core/src/main/java/im/actor/model/concurrency/TimerCompat.java
//

#ifndef _AMTimerCompat_H_
#define _AMTimerCompat_H_

#include "J2ObjC_header.h"
#include "im/actor/model/concurrency/AbsTimerCompat.h"

@protocol JavaLangRunnable;

@interface AMTimerCompat : AMAbsTimerCompat

#pragma mark Public

- (instancetype)initWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

- (void)cancel;

- (void)scheduleWithLong:(jlong)delay;

@end

J2OBJC_STATIC_INIT(AMTimerCompat)

FOUNDATION_EXPORT void AMTimerCompat_initWithJavaLangRunnable_(AMTimerCompat *self, id<JavaLangRunnable> runnable);

FOUNDATION_EXPORT AMTimerCompat *new_AMTimerCompat_initWithJavaLangRunnable_(id<JavaLangRunnable> runnable) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AMTimerCompat)

typedef AMTimerCompat ImActorModelConcurrencyTimerCompat;

#endif // _AMTimerCompat_H_
