//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core/src/main/java/im/actor/model/api/rpc/RequestImportContacts.java
//


#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/model/api/EmailToImport.h"
#include "im/actor/model/api/PhoneToImport.h"
#include "im/actor/model/api/rpc/RequestImportContacts.h"
#include "im/actor/model/droidkit/bser/Bser.h"
#include "im/actor/model/droidkit/bser/BserObject.h"
#include "im/actor/model/droidkit/bser/BserValues.h"
#include "im/actor/model/droidkit/bser/BserWriter.h"
#include "im/actor/model/network/parser/Request.h"
#include "java/io/IOException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface APRequestImportContacts () {
 @public
  id<JavaUtilList> phones_;
  id<JavaUtilList> emails_;
}

@end

J2OBJC_FIELD_SETTER(APRequestImportContacts, phones_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(APRequestImportContacts, emails_, id<JavaUtilList>)

@implementation APRequestImportContacts

+ (APRequestImportContacts *)fromBytesWithByteArray:(IOSByteArray *)data {
  return APRequestImportContacts_fromBytesWithByteArray_(data);
}

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)phones
                    withJavaUtilList:(id<JavaUtilList>)emails {
  APRequestImportContacts_initWithJavaUtilList_withJavaUtilList_(self, phones, emails);
  return self;
}

- (instancetype)init {
  APRequestImportContacts_init(self);
  return self;
}

- (id<JavaUtilList>)getPhones {
  return self->phones_;
}

- (id<JavaUtilList>)getEmails {
  return self->emails_;
}

- (void)parseWithBSBserValues:(BSBserValues *)values {
  id<JavaUtilList> _phones = new_JavaUtilArrayList_init();
  for (jint i = 0; i < [((BSBserValues *) nil_chk(values)) getRepeatedCountWithInt:1]; i++) {
    [_phones addWithId:new_APPhoneToImport_init()];
  }
  self->phones_ = [values getRepeatedObjWithInt:1 withJavaUtilList:_phones];
  id<JavaUtilList> _emails = new_JavaUtilArrayList_init();
  for (jint i = 0; i < [values getRepeatedCountWithInt:2]; i++) {
    [_emails addWithId:new_APEmailToImport_init()];
  }
  self->emails_ = [values getRepeatedObjWithInt:2 withJavaUtilList:_emails];
}

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer {
  [((BSBserWriter *) nil_chk(writer)) writeRepeatedObjWithInt:1 withJavaUtilList:self->phones_];
  [writer writeRepeatedObjWithInt:2 withJavaUtilList:self->emails_];
}

- (NSString *)description {
  NSString *res = @"rpc ImportContacts{";
  res = JreStrcat("$$", res, JreStrcat("$I", @"phones=", [((id<JavaUtilList>) nil_chk(self->phones_)) size]));
  res = JreStrcat("$$", res, JreStrcat("$I", @", emails=", [((id<JavaUtilList>) nil_chk(self->emails_)) size]));
  res = JreStrcat("$C", res, '}');
  return res;
}

- (jint)getHeaderKey {
  return APRequestImportContacts_HEADER;
}

@end

APRequestImportContacts *APRequestImportContacts_fromBytesWithByteArray_(IOSByteArray *data) {
  APRequestImportContacts_initialize();
  return ((APRequestImportContacts *) BSBser_parseWithBSBserObject_withByteArray_(new_APRequestImportContacts_init(), data));
}

void APRequestImportContacts_initWithJavaUtilList_withJavaUtilList_(APRequestImportContacts *self, id<JavaUtilList> phones, id<JavaUtilList> emails) {
  (void) APRequest_init(self);
  self->phones_ = phones;
  self->emails_ = emails;
}

APRequestImportContacts *new_APRequestImportContacts_initWithJavaUtilList_withJavaUtilList_(id<JavaUtilList> phones, id<JavaUtilList> emails) {
  APRequestImportContacts *self = [APRequestImportContacts alloc];
  APRequestImportContacts_initWithJavaUtilList_withJavaUtilList_(self, phones, emails);
  return self;
}

void APRequestImportContacts_init(APRequestImportContacts *self) {
  (void) APRequest_init(self);
}

APRequestImportContacts *new_APRequestImportContacts_init() {
  APRequestImportContacts *self = [APRequestImportContacts alloc];
  APRequestImportContacts_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(APRequestImportContacts)
