//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core/src/main/java/im/actor/model/api/OutPeer.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/api/OutPeer.h"
#include "im/actor/model/api/PeerType.h"
#include "im/actor/model/droidkit/bser/BserObject.h"
#include "im/actor/model/droidkit/bser/BserValues.h"
#include "im/actor/model/droidkit/bser/BserWriter.h"
#include "java/io/IOException.h"

@interface APOutPeer () {
 @public
  APPeerTypeEnum *type_;
  jint id__;
  jlong accessHash_;
}

@end

J2OBJC_FIELD_SETTER(APOutPeer, type_, APPeerTypeEnum *)

@implementation APOutPeer

- (instancetype)initWithAPPeerTypeEnum:(APPeerTypeEnum *)type
                               withInt:(jint)id_
                              withLong:(jlong)accessHash {
  APOutPeer_initWithAPPeerTypeEnum_withInt_withLong_(self, type, id_, accessHash);
  return self;
}

- (instancetype)init {
  APOutPeer_init(self);
  return self;
}

- (APPeerTypeEnum *)getType {
  return self->type_;
}

- (jint)getId {
  return self->id__;
}

- (jlong)getAccessHash {
  return self->accessHash_;
}

- (void)parseWithBSBserValues:(BSBserValues *)values {
  self->type_ = APPeerTypeEnum_parseWithInt_([((BSBserValues *) nil_chk(values)) getIntWithInt:1]);
  self->id__ = [values getIntWithInt:2];
  self->accessHash_ = [values getLongWithInt:3];
}

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer {
  if (self->type_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [((BSBserWriter *) nil_chk(writer)) writeIntWithInt:1 withInt:[((APPeerTypeEnum *) nil_chk(self->type_)) getValue]];
  [writer writeIntWithInt:2 withInt:self->id__];
  [writer writeLongWithInt:3 withLong:self->accessHash_];
}

- (NSString *)description {
  NSString *res = @"struct OutPeer{";
  res = JreStrcat("$$", res, JreStrcat("$@", @"type=", self->type_));
  res = JreStrcat("$$", res, JreStrcat("$I", @", id=", self->id__));
  res = JreStrcat("$C", res, '}');
  return res;
}

@end

void APOutPeer_initWithAPPeerTypeEnum_withInt_withLong_(APOutPeer *self, APPeerTypeEnum *type, jint id_, jlong accessHash) {
  (void) BSBserObject_init(self);
  self->type_ = type;
  self->id__ = id_;
  self->accessHash_ = accessHash;
}

APOutPeer *new_APOutPeer_initWithAPPeerTypeEnum_withInt_withLong_(APPeerTypeEnum *type, jint id_, jlong accessHash) {
  APOutPeer *self = [APOutPeer alloc];
  APOutPeer_initWithAPPeerTypeEnum_withInt_withLong_(self, type, id_, accessHash);
  return self;
}

void APOutPeer_init(APOutPeer *self) {
  (void) BSBserObject_init(self);
}

APOutPeer *new_APOutPeer_init() {
  APOutPeer *self = [APOutPeer alloc];
  APOutPeer_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(APOutPeer)
