platform :ios, '7.0'
workspace 'ActorApp'
xcodeproj 'ActorApp.xcodeproj'

target 'ActorApp' do
	xcodeproj 'ActorApp.xcodeproj'

	# Model
#	pod 'MMMutableMethods', :git => 'https://github.com/k06a/MMMutableMethods', :branch => 'dev', :tag => '0.0.7'
	pod 'j2objc-local', :git => 'https://github.com/actorapp/j2objc-local', :tag => 'v0.9.7'
	pod 'RegexKitLite', :inhibit_warnings => true
	pod 'CocoaAsyncSocket'
	pod 'FMDB'

	# UI
	pod 'VENTokenField'
	pod 'AsyncDisplayKit'
	pod 'SVProgressHUD'
	pod 'MBProgressHUD'
	pod 'PSTAlertController'
	pod 'PHFComposeBarView'
	pod 'DZNPhotoPickerController'
	pod 'HockeySDK'
	pod 'RMPhoneFormat', :git => 'https://github.com/actorapp/RMPhoneFormat'
	pod 'SlackTextViewController', :git => 'https://github.com/actorapp/SlackTextViewController'
    pod 'JTSImageViewController'
    pod 'PEPhotoCropEditor'
    pod 'TWMessageBarManager'
    pod 'LTNavigationBar'
    
    # Tracking
    pod 'SplunkMint-iOS'
    pod 'Mixpanel'
end