//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/modules/Typing.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/droidkit/actors/ActorRef.h"
#include "im/actor/model/droidkit/actors/ActorSystem.h"
#include "im/actor/model/droidkit/actors/Props.h"
#include "im/actor/model/entity/Peer.h"
#include "im/actor/model/modules/Modules.h"
#include "im/actor/model/modules/Typing.h"
#include "im/actor/model/modules/typing/OwnTypingActor.h"
#include "im/actor/model/modules/typing/TypingActor.h"

@interface ImActorModelModulesTyping () {
 @public
  ImActorModelDroidkitActorsActorRef *ownTypingActor_;
  ImActorModelDroidkitActorsActorRef *typingActor_;
}
@end

J2OBJC_FIELD_SETTER(ImActorModelModulesTyping, ownTypingActor_, ImActorModelDroidkitActorsActorRef *)
J2OBJC_FIELD_SETTER(ImActorModelModulesTyping, typingActor_, ImActorModelDroidkitActorsActorRef *)

@interface ImActorModelModulesTyping_$1 () {
 @public
  ImActorModelModulesModules *val$messenger_;
}
@end

J2OBJC_FIELD_SETTER(ImActorModelModulesTyping_$1, val$messenger_, ImActorModelModulesModules *)

@implementation ImActorModelModulesTyping

- (instancetype)initWithImActorModelModulesModules:(ImActorModelModulesModules *)messenger {
  if (self = [super initWithImActorModelModulesModules:messenger]) {
    self->ownTypingActor_ = [((ImActorModelDroidkitActorsActorSystem *) nil_chk(ImActorModelDroidkitActorsActorSystem_system())) actorOfWithImActorModelDroidkitActorsProps:ImActorModelDroidkitActorsProps_createWithIOSClass_withImActorModelDroidkitActorsActorCreator_(ImActorModelModulesTypingOwnTypingActor_class_(), [[ImActorModelModulesTyping_$1 alloc] initWithImActorModelModulesModules:messenger]) withNSString:@"actor/typing/own"];
    self->typingActor_ = ImActorModelModulesTypingTypingActor_getWithImActorModelModulesModules_(messenger);
  }
  return self;
}

- (void)onTypingWithImActorModelEntityPeer:(ImActorModelEntityPeer *)peer {
  [((ImActorModelDroidkitActorsActorRef *) nil_chk(ownTypingActor_)) sendWithId:[[ImActorModelModulesTypingOwnTypingActor_Typing alloc] initWithImActorModelEntityPeer:peer]];
}

- (void)copyAllFieldsTo:(ImActorModelModulesTyping *)other {
  [super copyAllFieldsTo:other];
  other->ownTypingActor_ = ownTypingActor_;
  other->typingActor_ = typingActor_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithImActorModelModulesModules:", "Typing", NULL, 0x1, NULL },
    { "onTypingWithImActorModelEntityPeer:", "onTyping", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ownTypingActor_", NULL, 0x2, "Lim.actor.model.droidkit.actors.ActorRef;", NULL,  },
    { "typingActor_", NULL, 0x2, "Lim.actor.model.droidkit.actors.ActorRef;", NULL,  },
  };
  static const J2ObjcClassInfo _ImActorModelModulesTyping = { 1, "Typing", "im.actor.model.modules", NULL, 0x1, 2, methods, 2, fields, 0, NULL};
  return &_ImActorModelModulesTyping;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ImActorModelModulesTyping)

@implementation ImActorModelModulesTyping_$1

- (ImActorModelModulesTypingOwnTypingActor *)create {
  return [[ImActorModelModulesTypingOwnTypingActor alloc] initWithImActorModelModulesModules:val$messenger_];
}

- (instancetype)initWithImActorModelModulesModules:(ImActorModelModulesModules *)capture$0 {
  val$messenger_ = capture$0;
  return [super init];
}

- (void)copyAllFieldsTo:(ImActorModelModulesTyping_$1 *)other {
  [super copyAllFieldsTo:other];
  other->val$messenger_ = val$messenger_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "create", NULL, "Lim.actor.model.modules.typing.OwnTypingActor;", 0x1, NULL },
    { "initWithImActorModelModulesModules:", "init", NULL, 0x0, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "val$messenger_", NULL, 0x1012, "Lim.actor.model.modules.Modules;", NULL,  },
  };
  static const J2ObjcClassInfo _ImActorModelModulesTyping_$1 = { 1, "$1", "im.actor.model.modules", "Typing", 0x8000, 2, methods, 1, fields, 0, NULL};
  return &_ImActorModelModulesTyping_$1;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ImActorModelModulesTyping_$1)
