package im.actor.model.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import com.droidkit.bser.Bser;
import com.droidkit.bser.BserObject;
import com.droidkit.bser.BserValues;
import com.droidkit.bser.BserWriter;
import java.io.IOException;
import im.actor.model.network.parser.*;
import java.util.List;
import java.util.ArrayList;
import im.actor.model.api.*;

public class RequestSubscribeFromOnline extends Request<ResponseVoid> {

    public static final int HEADER = 0x21;
    public static RequestSubscribeFromOnline fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestSubscribeFromOnline(), data);
    }

    private List<UserOutPeer> users;

    public RequestSubscribeFromOnline(List<UserOutPeer> users) {
        this.users = users;
    }

    public RequestSubscribeFromOnline() {

    }

    public List<UserOutPeer> getUsers() {
        return this.users;
    }

    @Override
    public void parse(BserValues values) throws IOException {
        List<UserOutPeer> _users = new ArrayList<UserOutPeer>();
        for (int i = 0; i < values.getRepeatedCount(1); i ++) {
            _users.add(new UserOutPeer());
        }
        this.users = values.getRepeatedObj(1, _users);
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
        writer.writeRepeatedObj(1, this.users);
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
