platform :ios, '8.0'
use_frameworks!

workspace 'ActorSDK'
xcodeproj 'ActorSDK.xcodeproj'
xcodeproj 'ActorApp.xcodeproj'

inhibit_all_warnings!

link_with 'ActorApp'

target 'ActorApp' do
    xcodeproj 'ActorApp.xcodeproj'

    # Tracking
    pod 'HockeySDK', '~> 3.8-RC'
    pod 'Fabric'
    pod 'Crashlytics'

end

target 'ActorSDK' do
    xcodeproj 'ActorSDK.xcodeproj'

    # J2Objc Runtime
    pod 'J2ObjC-Framework'

    # Core Tools
    pod 'RegexKitLite'
    pod 'CocoaAsyncSocket'
    pod 'zipzap'

    # Main UI
    pod 'SlackTextViewController'
    pod 'NYTPhotoViewer'
    pod 'TTTAttributedLabel'

    # Small UI
    pod 'PEPhotoCropEditor'
    pod 'VBFPopFlatButton'
    pod 'CLTokenInputView'
    pod 'SZTextView'
    
    # Alerts
    # TODO: Cleanup
    pod 'BlockAlertsAnd-ActionSheets'
    pod 'RMUniversalAlert'
    pod 'PSTAlertController'
    
    # Progress
    # TODO: Cleanup
    pod 'M13ProgressSuite'
    pod 'MBProgressHUD'
end
