//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/api/rpc/RequestSendAuthCode.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/model/api/rpc/RequestSendAuthCode.h"
#include "im/actor/model/droidkit/bser/Bser.h"
#include "im/actor/model/droidkit/bser/BserObject.h"
#include "im/actor/model/droidkit/bser/BserValues.h"
#include "im/actor/model/droidkit/bser/BserWriter.h"
#include "java/io/IOException.h"

@interface ImActorModelApiRpcRequestSendAuthCode () {
 @public
  jlong phoneNumber_;
  jint appId_;
  NSString *apiKey_;
}
@end

J2OBJC_FIELD_SETTER(ImActorModelApiRpcRequestSendAuthCode, apiKey_, NSString *)

@implementation ImActorModelApiRpcRequestSendAuthCode

+ (ImActorModelApiRpcRequestSendAuthCode *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ImActorModelApiRpcRequestSendAuthCode_fromBytesWithByteArray_(data);
}

- (instancetype)initWithLong:(jlong)phoneNumber
                     withInt:(jint)appId
                withNSString:(NSString *)apiKey {
  if (self = [super init]) {
    self->phoneNumber_ = phoneNumber;
    self->appId_ = appId;
    ImActorModelApiRpcRequestSendAuthCode_set_apiKey_(self, apiKey);
  }
  return self;
}

- (instancetype)init {
  return [super init];
}

- (jlong)getPhoneNumber {
  return self->phoneNumber_;
}

- (jint)getAppId {
  return self->appId_;
}

- (NSString *)getApiKey {
  return self->apiKey_;
}

- (void)parseWithImActorModelDroidkitBserBserValues:(ImActorModelDroidkitBserBserValues *)values {
  self->phoneNumber_ = [((ImActorModelDroidkitBserBserValues *) nil_chk(values)) getLongWithInt:1];
  self->appId_ = [values getIntWithInt:2];
  ImActorModelApiRpcRequestSendAuthCode_set_apiKey_(self, [values getStringWithInt:3]);
}

- (void)serializeWithImActorModelDroidkitBserBserWriter:(ImActorModelDroidkitBserBserWriter *)writer {
  [((ImActorModelDroidkitBserBserWriter *) nil_chk(writer)) writeLongWithInt:1 withLong:self->phoneNumber_];
  [writer writeIntWithInt:2 withInt:self->appId_];
  if (self->apiKey_ == nil) {
    @throw [[[JavaIoIOException alloc] init] autorelease];
  }
  [writer writeStringWithInt:3 withNSString:self->apiKey_];
}

- (jint)getHeaderKey {
  return ImActorModelApiRpcRequestSendAuthCode_HEADER;
}

- (void)dealloc {
  RELEASE_(apiKey_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ImActorModelApiRpcRequestSendAuthCode *)other {
  [super copyAllFieldsTo:other];
  other->phoneNumber_ = phoneNumber_;
  other->appId_ = appId_;
  ImActorModelApiRpcRequestSendAuthCode_set_apiKey_(other, apiKey_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.model.api.rpc.RequestSendAuthCode;", 0x9, "Ljava.io.IOException;" },
    { "initWithLong:withInt:withNSString:", "RequestSendAuthCode", NULL, 0x1, NULL },
    { "init", "RequestSendAuthCode", NULL, 0x1, NULL },
    { "getPhoneNumber", NULL, "J", 0x1, NULL },
    { "getAppId", NULL, "I", 0x1, NULL },
    { "getApiKey", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "parseWithImActorModelDroidkitBserBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;" },
    { "serializeWithImActorModelDroidkitBserBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;" },
    { "getHeaderKey", NULL, "I", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER_", NULL, 0x19, "I", NULL, .constantValue.asInt = ImActorModelApiRpcRequestSendAuthCode_HEADER },
    { "phoneNumber_", NULL, 0x2, "J", NULL,  },
    { "appId_", NULL, 0x2, "I", NULL,  },
    { "apiKey_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static const char *superclass_type_args[] = {"Lim.actor.model.api.rpc.ResponseSendAuthCode;"};
  static const J2ObjcClassInfo _ImActorModelApiRpcRequestSendAuthCode = { 1, "RequestSendAuthCode", "im.actor.model.api.rpc", NULL, 0x1, 9, methods, 4, fields, 1, superclass_type_args};
  return &_ImActorModelApiRpcRequestSendAuthCode;
}

@end

ImActorModelApiRpcRequestSendAuthCode *ImActorModelApiRpcRequestSendAuthCode_fromBytesWithByteArray_(IOSByteArray *data) {
  ImActorModelApiRpcRequestSendAuthCode_init();
  return ((ImActorModelApiRpcRequestSendAuthCode *) ImActorModelDroidkitBserBser_parseWithImActorModelDroidkitBserBserObject_withByteArray_([[[ImActorModelApiRpcRequestSendAuthCode alloc] init] autorelease], data));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ImActorModelApiRpcRequestSendAuthCode)
