//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/api/rpc/ResponseAuth.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/droidkit/bser/Bser.h"
#include "com/droidkit/bser/BserObject.h"
#include "com/droidkit/bser/BserValues.h"
#include "com/droidkit/bser/BserWriter.h"
#include "im/actor/model/api/Config.h"
#include "im/actor/model/api/ContactRecord.h"
#include "im/actor/model/api/User.h"
#include "im/actor/model/api/rpc/ResponseAuth.h"
#include "java/io/IOException.h"
#include "java/util/List.h"

@interface ImActorModelApiRpcResponseAuth () {
 @public
  jlong publicKeyHash_;
  ImActorModelApiUser *user_;
  id<JavaUtilList> contacts_;
  ImActorModelApiConfig *config_;
}
@end

J2OBJC_FIELD_SETTER(ImActorModelApiRpcResponseAuth, user_, ImActorModelApiUser *)
J2OBJC_FIELD_SETTER(ImActorModelApiRpcResponseAuth, contacts_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ImActorModelApiRpcResponseAuth, config_, ImActorModelApiConfig *)

@implementation ImActorModelApiRpcResponseAuth

+ (ImActorModelApiRpcResponseAuth *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ImActorModelApiRpcResponseAuth_fromBytesWithByteArray_(data);
}

- (instancetype)initWithLong:(jlong)publicKeyHash
     withImActorModelApiUser:(ImActorModelApiUser *)user
            withJavaUtilList:(id<JavaUtilList>)contacts
   withImActorModelApiConfig:(ImActorModelApiConfig *)config {
  if (self = [super init]) {
    self->publicKeyHash_ = publicKeyHash;
    ImActorModelApiRpcResponseAuth_set_user_(self, user);
    ImActorModelApiRpcResponseAuth_set_contacts_(self, contacts);
    ImActorModelApiRpcResponseAuth_set_config_(self, config);
  }
  return self;
}

- (instancetype)init {
  return [super init];
}

- (jlong)getPublicKeyHash {
  return self->publicKeyHash_;
}

- (ImActorModelApiUser *)getUser {
  return self->user_;
}

- (id<JavaUtilList>)getContacts {
  return self->contacts_;
}

- (ImActorModelApiConfig *)getConfig {
  return self->config_;
}

- (void)parseWithComDroidkitBserBserValues:(ComDroidkitBserBserValues *)values {
  self->publicKeyHash_ = [((ComDroidkitBserBserValues *) nil_chk(values)) getLongWithInt:1];
  ImActorModelApiRpcResponseAuth_set_user_(self, [values getObjWithInt:2 withIOSClass:ImActorModelApiUser_class_()]);
  ImActorModelApiRpcResponseAuth_set_contacts_(self, [values getRepeatedObjWithInt:4 withIOSClass:ImActorModelApiContactRecord_class_()]);
  ImActorModelApiRpcResponseAuth_set_config_(self, [values getObjWithInt:3 withIOSClass:ImActorModelApiConfig_class_()]);
}

- (void)serializeWithComDroidkitBserBserWriter:(ComDroidkitBserBserWriter *)writer {
  [((ComDroidkitBserBserWriter *) nil_chk(writer)) writeLongWithInt:1 withLong:self->publicKeyHash_];
  if (self->user_ == nil) {
    @throw [[[JavaIoIOException alloc] init] autorelease];
  }
  [writer writeObjectWithInt:2 withComDroidkitBserBserObject:self->user_];
  [writer writeRepeatedObjWithInt:4 withJavaUtilList:self->contacts_];
  if (self->config_ == nil) {
    @throw [[[JavaIoIOException alloc] init] autorelease];
  }
  [writer writeObjectWithInt:3 withComDroidkitBserBserObject:self->config_];
}

- (jint)getHeaderKey {
  return ImActorModelApiRpcResponseAuth_HEADER;
}

- (void)dealloc {
  RELEASE_(user_);
  RELEASE_(contacts_);
  RELEASE_(config_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ImActorModelApiRpcResponseAuth *)other {
  [super copyAllFieldsTo:other];
  other->publicKeyHash_ = publicKeyHash_;
  ImActorModelApiRpcResponseAuth_set_user_(other, user_);
  ImActorModelApiRpcResponseAuth_set_contacts_(other, contacts_);
  ImActorModelApiRpcResponseAuth_set_config_(other, config_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.model.api.rpc.ResponseAuth;", 0x9, "Ljava.io.IOException;" },
    { "initWithLong:withImActorModelApiUser:withJavaUtilList:withImActorModelApiConfig:", "ResponseAuth", NULL, 0x1, NULL },
    { "init", "ResponseAuth", NULL, 0x1, NULL },
    { "getPublicKeyHash", NULL, "J", 0x1, NULL },
    { "getUser", NULL, "Lim.actor.model.api.User;", 0x1, NULL },
    { "getContacts", NULL, "Ljava.util.List;", 0x1, NULL },
    { "getConfig", NULL, "Lim.actor.model.api.Config;", 0x1, NULL },
    { "parseWithComDroidkitBserBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;" },
    { "serializeWithComDroidkitBserBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;" },
    { "getHeaderKey", NULL, "I", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER_", NULL, 0x19, "I", NULL, .constantValue.asInt = ImActorModelApiRpcResponseAuth_HEADER },
    { "publicKeyHash_", NULL, 0x2, "J", NULL,  },
    { "user_", NULL, 0x2, "Lim.actor.model.api.User;", NULL,  },
    { "contacts_", NULL, 0x2, "Ljava.util.List;", NULL,  },
    { "config_", NULL, 0x2, "Lim.actor.model.api.Config;", NULL,  },
  };
  static const J2ObjcClassInfo _ImActorModelApiRpcResponseAuth = { 1, "ResponseAuth", "im.actor.model.api.rpc", NULL, 0x1, 10, methods, 5, fields, 0, NULL};
  return &_ImActorModelApiRpcResponseAuth;
}

@end

ImActorModelApiRpcResponseAuth *ImActorModelApiRpcResponseAuth_fromBytesWithByteArray_(IOSByteArray *data) {
  ImActorModelApiRpcResponseAuth_init();
  return ((ImActorModelApiRpcResponseAuth *) ComDroidkitBserBser_parseWithIOSClass_withByteArray_(ImActorModelApiRpcResponseAuth_class_(), data));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ImActorModelApiRpcResponseAuth)
