//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/ocsp/OCSPResponse.java
//

#ifndef _OrgBouncycastleAsn1OcspOCSPResponse_H_
#define _OrgBouncycastleAsn1OcspOCSPResponse_H_

@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Sequence;
@class OrgBouncycastleAsn1ASN1TaggedObject;
@class OrgBouncycastleAsn1OcspOCSPResponseStatus;
@class OrgBouncycastleAsn1OcspResponseBytes;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

@interface OrgBouncycastleAsn1OcspOCSPResponse : OrgBouncycastleAsn1ASN1Object {
 @public
  OrgBouncycastleAsn1OcspOCSPResponseStatus *responseStatus_;
  OrgBouncycastleAsn1OcspResponseBytes *responseBytes_;
}

- (instancetype)initWithOrgBouncycastleAsn1OcspOCSPResponseStatus:(OrgBouncycastleAsn1OcspOCSPResponseStatus *)responseStatus
                         withOrgBouncycastleAsn1OcspResponseBytes:(OrgBouncycastleAsn1OcspResponseBytes *)responseBytes;

+ (OrgBouncycastleAsn1OcspOCSPResponse *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                                withBoolean:(jboolean)explicit_;

+ (OrgBouncycastleAsn1OcspOCSPResponse *)getInstanceWithId:(id)obj;

- (OrgBouncycastleAsn1OcspOCSPResponseStatus *)getResponseStatus;

- (OrgBouncycastleAsn1OcspResponseBytes *)getResponseBytes;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1OcspOCSPResponse)

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1OcspOCSPResponse, responseStatus_, OrgBouncycastleAsn1OcspOCSPResponseStatus *)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1OcspOCSPResponse, responseBytes_, OrgBouncycastleAsn1OcspResponseBytes *)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1OcspOCSPResponse *OrgBouncycastleAsn1OcspOCSPResponse_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_);

FOUNDATION_EXPORT OrgBouncycastleAsn1OcspOCSPResponse *OrgBouncycastleAsn1OcspOCSPResponse_getInstanceWithId_(id obj);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1OcspOCSPResponse)

#endif // _OrgBouncycastleAsn1OcspOCSPResponse_H_
