//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/org/bouncycastle/asn1/ocsp/RevokedInfo.java
//

#ifndef _OrgBouncycastleAsn1OcspRevokedInfo_H_
#define _OrgBouncycastleAsn1OcspRevokedInfo_H_

@class OrgBouncycastleAsn1ASN1GeneralizedTime;
@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1Sequence;
@class OrgBouncycastleAsn1ASN1TaggedObject;
@class OrgBouncycastleAsn1X509CRLReason;

#include "J2ObjC_header.h"
#include "org/bouncycastle/asn1/ASN1Object.h"

@interface OrgBouncycastleAsn1OcspRevokedInfo : OrgBouncycastleAsn1ASN1Object {
}

- (instancetype)initWithOrgBouncycastleAsn1ASN1GeneralizedTime:(OrgBouncycastleAsn1ASN1GeneralizedTime *)revocationTime
                          withOrgBouncycastleAsn1X509CRLReason:(OrgBouncycastleAsn1X509CRLReason *)revocationReason;

+ (OrgBouncycastleAsn1OcspRevokedInfo *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                               withBoolean:(jboolean)explicit_;

+ (OrgBouncycastleAsn1OcspRevokedInfo *)getInstanceWithId:(id)obj;

- (OrgBouncycastleAsn1ASN1GeneralizedTime *)getRevocationTime;

- (OrgBouncycastleAsn1X509CRLReason *)getRevocationReason;

- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1OcspRevokedInfo)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgBouncycastleAsn1OcspRevokedInfo *OrgBouncycastleAsn1OcspRevokedInfo_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_);

FOUNDATION_EXPORT OrgBouncycastleAsn1OcspRevokedInfo *OrgBouncycastleAsn1OcspRevokedInfo_getInstanceWithId_(id obj);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1OcspRevokedInfo)

#endif // _OrgBouncycastleAsn1OcspRevokedInfo_H_
