//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/mvvm/ListEngineItem.java
//

#ifndef _AMListEngineItem_H_
#define _AMListEngineItem_H_

#include "J2ObjC_header.h"

@protocol AMListEngineItem < NSObject, JavaObject >

- (jlong)getListId;

- (jlong)getListSortKey;

@end

J2OBJC_EMPTY_STATIC_INIT(AMListEngineItem)

#define ImActorModelMvvmListEngineItem AMListEngineItem

J2OBJC_TYPE_LITERAL_HEADER(AMListEngineItem)

#endif // _AMListEngineItem_H_
