//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core/src/main/java/im/actor/model/api/updates/UpdateUserAboutChanged.java
//


#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/model/api/updates/UpdateUserAboutChanged.h"
#include "im/actor/model/droidkit/bser/Bser.h"
#include "im/actor/model/droidkit/bser/BserObject.h"
#include "im/actor/model/droidkit/bser/BserValues.h"
#include "im/actor/model/droidkit/bser/BserWriter.h"
#include "im/actor/model/network/parser/Update.h"
#include "java/io/IOException.h"

@interface APUpdateUserAboutChanged () {
 @public
  jint uid_;
  NSString *about_;
}

@end

J2OBJC_FIELD_SETTER(APUpdateUserAboutChanged, about_, NSString *)

@implementation APUpdateUserAboutChanged

+ (APUpdateUserAboutChanged *)fromBytesWithByteArray:(IOSByteArray *)data {
  return APUpdateUserAboutChanged_fromBytesWithByteArray_(data);
}

- (instancetype)initWithInt:(jint)uid
               withNSString:(NSString *)about {
  APUpdateUserAboutChanged_initWithInt_withNSString_(self, uid, about);
  return self;
}

- (instancetype)init {
  APUpdateUserAboutChanged_init(self);
  return self;
}

- (jint)getUid {
  return self->uid_;
}

- (NSString *)getAbout {
  return self->about_;
}

- (void)parseWithBSBserValues:(BSBserValues *)values {
  self->uid_ = [((BSBserValues *) nil_chk(values)) getIntWithInt:1];
  self->about_ = [values optStringWithInt:2];
}

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer {
  [((BSBserWriter *) nil_chk(writer)) writeIntWithInt:1 withInt:self->uid_];
  if (self->about_ != nil) {
    [writer writeStringWithInt:2 withNSString:self->about_];
  }
}

- (NSString *)description {
  NSString *res = @"update UserAboutChanged{";
  res = JreStrcat("$$", res, JreStrcat("$I", @"uid=", self->uid_));
  res = JreStrcat("$$", res, JreStrcat("$$", @", about=", self->about_));
  res = JreStrcat("$C", res, '}');
  return res;
}

- (jint)getHeaderKey {
  return APUpdateUserAboutChanged_HEADER;
}

@end

APUpdateUserAboutChanged *APUpdateUserAboutChanged_fromBytesWithByteArray_(IOSByteArray *data) {
  APUpdateUserAboutChanged_initialize();
  return ((APUpdateUserAboutChanged *) BSBser_parseWithBSBserObject_withByteArray_(new_APUpdateUserAboutChanged_init(), data));
}

void APUpdateUserAboutChanged_initWithInt_withNSString_(APUpdateUserAboutChanged *self, jint uid, NSString *about) {
  (void) APUpdate_init(self);
  self->uid_ = uid;
  self->about_ = about;
}

APUpdateUserAboutChanged *new_APUpdateUserAboutChanged_initWithInt_withNSString_(jint uid, NSString *about) {
  APUpdateUserAboutChanged *self = [APUpdateUserAboutChanged alloc];
  APUpdateUserAboutChanged_initWithInt_withNSString_(self, uid, about);
  return self;
}

void APUpdateUserAboutChanged_init(APUpdateUserAboutChanged *self) {
  (void) APUpdate_init(self);
}

APUpdateUserAboutChanged *new_APUpdateUserAboutChanged_init() {
  APUpdateUserAboutChanged *self = [APUpdateUserAboutChanged alloc];
  APUpdateUserAboutChanged_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(APUpdateUserAboutChanged)
