package im.actor.core.api.rpc;
/*
 *  Generated by the Actor API Scheme generator.  DO NOT EDIT!
 */

import im.actor.runtime.bser.*;
import im.actor.core.network.parser.*;

import java.io.IOException;

public class RequestInitVoxSupport extends Request<ResponseInitVoxSupport> {

    public static final int HEADER = 0x82;
    public static RequestInitVoxSupport fromBytes(byte[] data) throws IOException {
        return Bser.parse(new RequestInitVoxSupport(), data);
    }


    public RequestInitVoxSupport() {

    }

    @Override
    public void parse(BserValues values) throws IOException {
    }

    @Override
    public void serialize(BserWriter writer) throws IOException {
    }

    @Override
    public String toString() {
        String res = "rpc InitVoxSupport{";
        res += "}";
        return res;
    }

    @Override
    public int getHeaderKey() {
        return HEADER;
    }
}
