//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-apps/core-crypto/src/main/java/org/bouncycastle/util/IPAddress.java
//

#ifndef _OrgBouncycastleUtilIPAddress_H_
#define _OrgBouncycastleUtilIPAddress_H_

#include "J2ObjC_header.h"

@interface OrgBouncycastleUtilIPAddress : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)isValidWithNSString:(NSString *)address;

+ (jboolean)isValidIPv4WithNSString:(NSString *)address;

+ (jboolean)isValidIPv4WithNetmaskWithNSString:(NSString *)address;

+ (jboolean)isValidIPv6WithNSString:(NSString *)address;

+ (jboolean)isValidIPv6WithNetmaskWithNSString:(NSString *)address;

+ (jboolean)isValidWithNetMaskWithNSString:(NSString *)address;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleUtilIPAddress)

FOUNDATION_EXPORT jboolean OrgBouncycastleUtilIPAddress_isValidWithNSString_(NSString *address);

FOUNDATION_EXPORT jboolean OrgBouncycastleUtilIPAddress_isValidWithNetMaskWithNSString_(NSString *address);

FOUNDATION_EXPORT jboolean OrgBouncycastleUtilIPAddress_isValidIPv4WithNSString_(NSString *address);

FOUNDATION_EXPORT jboolean OrgBouncycastleUtilIPAddress_isValidIPv4WithNetmaskWithNSString_(NSString *address);

FOUNDATION_EXPORT jboolean OrgBouncycastleUtilIPAddress_isValidIPv6WithNetmaskWithNSString_(NSString *address);

FOUNDATION_EXPORT jboolean OrgBouncycastleUtilIPAddress_isValidIPv6WithNSString_(NSString *address);

FOUNDATION_EXPORT void OrgBouncycastleUtilIPAddress_init(OrgBouncycastleUtilIPAddress *self);

FOUNDATION_EXPORT OrgBouncycastleUtilIPAddress *new_OrgBouncycastleUtilIPAddress_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleUtilIPAddress)

#endif // _OrgBouncycastleUtilIPAddress_H_
