//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/droidkit/actors/MailboxCreator.java
//

#include "J2ObjC_source.h"
#include "im/actor/model/droidkit/actors/MailboxCreator.h"
#include "im/actor/model/droidkit/actors/mailbox/Mailbox.h"
#include "im/actor/model/droidkit/actors/mailbox/MailboxesQueue.h"

@interface DKMailboxCreator : NSObject
@end

@implementation DKMailboxCreator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createMailboxWithDKMailboxesQueue:", "createMailbox", "Lim.actor.model.droidkit.actors.mailbox.Mailbox;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _DKMailboxCreator = { 1, "MailboxCreator", "im.actor.model.droidkit.actors", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_DKMailboxCreator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DKMailboxCreator)
