//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core/src/main/java/im/actor/model/droidkit/actors/ActorRef.java
//

#ifndef _DKActorRef_H_
#define _DKActorRef_H_

#include "J2ObjC_header.h"

@class DKActorDispatcher;
@class DKActorEndpoint;
@class DKActorSystem;

@interface DKActorRef : NSObject

#pragma mark Public

- (instancetype)initWithDKActorEndpoint:(DKActorEndpoint *)endpoint
                      withDKActorSystem:(DKActorSystem *)system
                  withDKActorDispatcher:(DKActorDispatcher *)dispatcher
                           withNSString:(NSString *)path;

- (void)cancelMessageWithId:(id)message;

- (void)cancelMessageWithId:(id)message
             withDKActorRef:(DKActorRef *)sender;

- (NSString *)getPath;

- (void)sendWithId:(id)message;

- (void)sendWithId:(id)message
    withDKActorRef:(DKActorRef *)sender;

- (void)sendWithId:(id)message
          withLong:(jlong)delay;

- (void)sendWithId:(id)message
          withLong:(jlong)delay
    withDKActorRef:(DKActorRef *)sender;

- (void)sendOnceWithId:(id)message;

- (void)sendOnceWithId:(id)message
        withDKActorRef:(DKActorRef *)sender;

- (void)sendOnceWithId:(id)message
              withLong:(jlong)delay;

- (void)sendOnceWithId:(id)message
              withLong:(jlong)delay
        withDKActorRef:(DKActorRef *)sender;

- (DKActorSystem *)system;

@end

J2OBJC_EMPTY_STATIC_INIT(DKActorRef)

FOUNDATION_EXPORT void DKActorRef_initWithDKActorEndpoint_withDKActorSystem_withDKActorDispatcher_withNSString_(DKActorRef *self, DKActorEndpoint *endpoint, DKActorSystem *system, DKActorDispatcher *dispatcher, NSString *path);

FOUNDATION_EXPORT DKActorRef *new_DKActorRef_initWithDKActorEndpoint_withDKActorSystem_withDKActorDispatcher_withNSString_(DKActorEndpoint *endpoint, DKActorSystem *system, DKActorDispatcher *dispatcher, NSString *path) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(DKActorRef)

typedef DKActorRef ImActorModelDroidkitActorsActorRef;

#endif // _DKActorRef_H_
