//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/core/src/main/java/im/actor/model/network/AuthKeyStorage.java
//


#include "J2ObjC_source.h"
#include "im/actor/model/network/AuthKeyStorage.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AMAuthKeyStorage)
