//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/library/core/src/main/java/im/actor/model/network/RpcTimeoutException.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/network/RpcException.h"
#include "im/actor/model/network/RpcTimeoutException.h"

@implementation AMRpcTimeoutException

- (instancetype)init {
  AMRpcTimeoutException_init(self);
  return self;
}

@end

void AMRpcTimeoutException_init(AMRpcTimeoutException *self) {
  (void) AMRpcException_initWithNSString_withInt_withNSString_withBoolean_withByteArray_(self, @"TIMEOUT", 500, @"Request timeout", YES, nil);
}

AMRpcTimeoutException *new_AMRpcTimeoutException_init() {
  AMRpcTimeoutException *self = [AMRpcTimeoutException alloc];
  AMRpcTimeoutException_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AMRpcTimeoutException)
