//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-model/actor-ios/build/java/im/actor/model/network/mtp/entity/UnsentMessage.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/model/droidkit/bser/DataInput.h"
#include "im/actor/model/droidkit/bser/DataOutput.h"
#include "im/actor/model/network/mtp/entity/UnsentMessage.h"
#include "java/io/IOException.h"

@interface MTUnsentMessage () {
 @public
  jlong messageId_;
  jint len_;
}
@end

@implementation MTUnsentMessage

- (instancetype)initWithLong:(jlong)messageId
                     withInt:(jint)len {
  if (self = [super init]) {
    self->messageId_ = messageId;
    self->len_ = len;
  }
  return self;
}

- (instancetype)initWithBSDataInput:(BSDataInput *)stream {
  return [super initWithBSDataInput:stream];
}

- (jlong)getMessageId {
  return messageId_;
}

- (jint)getLen {
  return len_;
}

- (jbyte)getHeader {
  return MTUnsentMessage_HEADER;
}

- (void)writeBodyWithBSDataOutput:(BSDataOutput *)bs {
  [((BSDataOutput *) nil_chk(bs)) writeLongWithLong:messageId_];
  [bs writeIntWithInt:len_];
}

- (void)readBodyWithBSDataInput:(BSDataInput *)bs {
  messageId_ = [((BSDataInput *) nil_chk(bs)) readLong];
  len_ = [bs readInt];
}

- (NSString *)description {
  return JreStrcat("$JC", @"UnsentMessage[", messageId_, ']');
}

- (void)copyAllFieldsTo:(MTUnsentMessage *)other {
  [super copyAllFieldsTo:other];
  other->messageId_ = messageId_;
  other->len_ = len_;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(MTUnsentMessage)
