//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-platform/actor-apps/core/src/main/java/im/actor/model/api/updates/UpdateUserLocalNameChanged.java
//

#ifndef _APUpdateUserLocalNameChanged_H_
#define _APUpdateUserLocalNameChanged_H_

#include "J2ObjC_header.h"
#include "im/actor/model/network/parser/Update.h"

@class BSBserValues;
@class BSBserWriter;
@class IOSByteArray;

#define APUpdateUserLocalNameChanged_HEADER 51

@interface APUpdateUserLocalNameChanged : APUpdate

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)uid
               withNSString:(NSString *)localName;

+ (APUpdateUserLocalNameChanged *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (NSString *)getLocalName;

- (jint)getUid;

- (void)parseWithBSBserValues:(BSBserValues *)values;

- (void)serializeWithBSBserWriter:(BSBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(APUpdateUserLocalNameChanged)

J2OBJC_STATIC_FIELD_GETTER(APUpdateUserLocalNameChanged, HEADER, jint)

FOUNDATION_EXPORT APUpdateUserLocalNameChanged *APUpdateUserLocalNameChanged_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void APUpdateUserLocalNameChanged_initWithInt_withNSString_(APUpdateUserLocalNameChanged *self, jint uid, NSString *localName);

FOUNDATION_EXPORT APUpdateUserLocalNameChanged *new_APUpdateUserLocalNameChanged_initWithInt_withNSString_(jint uid, NSString *localName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void APUpdateUserLocalNameChanged_init(APUpdateUserLocalNameChanged *self);

FOUNDATION_EXPORT APUpdateUserLocalNameChanged *new_APUpdateUserLocalNameChanged_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(APUpdateUserLocalNameChanged)

typedef APUpdateUserLocalNameChanged ImActorModelApiUpdatesUpdateUserLocalNameChanged;

#endif // _APUpdateUserLocalNameChanged_H_
